### ISSUE TITLE
1.4.1 

### ISSUE THREAD

**Issue by rezazealott** [HamedAp/Ssh-User-management#10]
این آپدیت یوزرهای آنلاین رو دیگه نشون نمیده

**Comment by HamedAp** [comment]
> این آپدیت یوزرهای آنلاین رو دیگه نشون نمیده

بله تا شب مشکلش حل میشه و امکانات جدید میاد . 
اگه میتونین دستور نصب رو بزنین ( از پنل اپدیت نکنین ) و تست کنین قسمت انلاین درست میشه ؟

**Comment by rezazealott** [comment]
نه متاسفانه اوکی نشد

**Comment by HamedAp** [comment]
تا امشب انشالله حل میشه مشکلش . 
اپدیت 2.0 دارم میزنم

**Comment by HamedAp** [comment]
سیستم عامل شما چیه ؟ 
سنتوس ؟ اوبونتو ؟

**Comment by rezazealott** [comment]
ubuntu

> سیستم عامل شما چیه ؟ سنتوس ؟ اوبونتو ؟

**Comment by HamedAp** [comment]
آپدیت جدید با امکانات خیلی بیشتر و بهتر تقریبا امادست . 
اجازه بدین کامل رفع باگ بشه و فردا اپدیت رو ثبت می کنم .

**Comment by rezazealott** [comment]
ممنون ازتون

**Comment by fsh230** [comment]
سلام مهندس واقعا دمت گرم 
ما مشتاقانه منتظریم تا آپدیت بعدی رو انتشار بدی

**Comment by Sultanspeed** [comment]
سلام

ارور میده یا اینکه همه مراحل را درست پیش میرم

پنل بالا نمیاد

Not Found

The requested URL was not found on this server.
Apache/2.4.29 (Ubuntu) Server at 165.232.182.101 Port 80

**Comment by HamedAp** [comment]
> سلام
> 
> ارور میده با اینکه همه مراحل را درست پیش میرم
> 
> پنل بالا نمیاد اوبونتو 18 Not Found
> 
> The requested URL was not found on this server. Apache/2.4.29 (Ubuntu) Server at 165.232.2.101 Port 80

در حال تست پنل جدید بودم . الان دوباره دستور نصب رو بزنین مشکل حل میشه
