### ISSUE TITLE
هزینه پنل پرو

### ISSUE THREAD

**Issue by FarzadMohtasham** [HamedAp/Ssh-User-management#100]
سلام برادر، خسته نباشی، هزینه پنل پرو چنده؟

**Comment by HamedAp** [comment]
سلام 
۱۰ دلار به صورت مادام العمر و با قابلیت تغییر ای پی

**Comment by FarzadMohtasham** [comment]
از کجا باید پرداخت کنم؟

**Comment by HamedAp** [comment]
تو تلگرام به ای دی زیر پیام بدین :

@Shahanpanelsupport
