### ISSUE TITLE
The requested URL was not found on this server.

### ISSUE THREAD

**Issue by hamedhosseini143** [HamedAp/Ssh-User-management#101]
after instal error:

Not Found
The requested URL was not found on this server.

Apache/2.4.29 (Ubuntu) Server at  my ip Port 80

**Comment by HamedAp** [comment]
دستور نصب رو دوباره بزنین . احتمالا کامل نصب نشده

**Comment by hamedhosseini143** [comment]
نه نشد

**Comment by hamedhosseini143** [comment]
Connection failed: Access denied for user 'admin'@'localhost' (using password: YES)

**Comment by hamedhosseini143** [comment]
یعد نصب جدید

**Comment by HamedAp** [comment]
دستور زیر رو بزنین و دوباره دستور نصب بزنین :
`mysql -e "drop user admin@localhost;use ShaHaN;drop table setting;"`
