### ISSUE TITLE
محدودیت کاربر

### ISSUE THREAD

**Issue by mmdjvdad** [HamedAp/Ssh-User-management#104]
سلام، محدودیت کاربر کار نمیکنه. اکانت روی تک کاربره گزاشتم و با سه تا گوشی بهش وصل شدم. هر سه تا متصل بود و قطع نمیکرد فقط توی نرم افزار ای پی قرمز نشون میداد.

**Comment by HamedAp** [comment]
سلام .
توی تنظیمات محدودیت کاربر رو فعال کنین
