### ISSUE TITLE
ارور آپاچی بعد از نصب

### ISSUE THREAD

**Issue by Sultanspeed** [HamedAp/Ssh-User-management#11]
سلام

بعد از نصب کامل و هنگام بالا اومدن پنل در اوبونتو 18 و 20

ارور آپاچی می‌دهد

Not Found

The requested URL was not found on this server.
Apache/2.4.29 (Ubuntu) Server at 165.000 Port 80

**Comment by HamedAp** [comment]
> سلام
> 
> بعد از نصب کامل و هنگام بالا اومدن پنل در اوبونتو 18 و 20
> 
> ارور آپاچی می‌دهد
> 
> Not Found
> 
> The requested URL was not found on this server. Apache/2.4.29 (Ubuntu) Server at 165.000 Port 80

قبلا پنل رو داشتید یا اولین باره نصب میکنین ؟

**Comment by Sultanspeed** [comment]
> > سلام
> > بعد از نصب کامل و هنگام بالا اومدن پنل در اوبونتو 18 و 20
> > ارور آپاچی می‌دهد
> > Not Found
> > The requested URL was not found on this server. Apache/2.4.29 (Ubuntu) Server at 165.000 Port 80
> 
> قبلا پنل رو داشتید یا اولین باره نصب میکنین ؟

خیر بار اول هست

**Comment by HamedAp** [comment]
امکانش هست عکس بفرستید که کدوم قسمت خطا میده ؟

**Comment by Sultanspeed** [comment]
بله
![Screenshot_2023-02-17-02-17-53-832_org mozilla firefox](https://user-images.githubusercontent.com/118662758/219594352-b73c8feb-b5f3-4bc7-8b7c-6aeccc1d24a0.jpg)

**Comment by HamedAp** [comment]
ادرس اشتباه زدین . 
Http://Ip/p/index.php

**Comment by Sultanspeed** [comment]
دقیق قیمت ip سرور را زدم قسمت پورت هم همون پورت 5829

باید چه جوری وارد کنم؟

**Comment by HamedAp** [comment]
http://165.0.182.101/p/index.php
ادرس پنل این هستش .

**Comment by Sultanspeed** [comment]
بازم ارور داد بزرگوار

عجب داستانی شده
![IMG_20230217_123202](https://user-images.githubusercontent.com/118662758/219600275-85a4fe3d-6846-4036-a095-b388cba95508.jpg)

**Comment by HamedAp** [comment]
اگه امکانش هست تو تلگرام پیام بدین بررسی کنم .
Tg id : hamed_ap
