### ISSUE TITLE
سلام بعد از ارتقا پنل به vip باید فایل های جدید روی سایت اضافه کنیم یا اتومات برامون فعال میشه؟

### ISSUE THREAD

**Issue by amir77xj** [HamedAp/Ssh-User-management#112]
سلام بعد از ارتقا پنل به vip باید فایل های جدید روی سایت اضافه کنیم یا اتومات برامون فعال میشه؟

_Originally posted by @amir77xj in https://github.com/HamedAp/Ssh-User-management/discussions/108_

**Comment by HamedAp** [comment]
اتوماتیک فعال میشه
