### ISSUE TITLE
نصب پنل

### ISSUE THREAD

**Issue by cyberir** [HamedAp/Ssh-User-management#113]
بعد از نصب پنل با دستور 
bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/install.sh --ipv4)
با موفقیت نصب شد 
در اخر به من ادرس پنل 
Panel Link : http://IPAddress/p/index.php
میدهد اما اصلا هیچ صفحه ای باز نمیکند مشکل از کدام قسمت میباشد ؟

**Comment by cyberir** [comment]
مشکل برطرف کردم با دستور زیر برطرف میشود 
sudo ufw allow 80/tcp

**Comment by cyberir** [comment]
اما مشکل این هستش که اصلا رایگان نمیباشد باید برای خرید لایسنس 10 دلار پرداخت کنید که این موضوع خیلی ناراحت کننده میباشد

**Comment by HamedAp** [comment]
پنل دو نسخه دارد 
حرفه ای و رایگان
میتونین از رایگان استفاده کنین

**Comment by HamedAp** [comment]
> 

به پشتیبانی پیام بدین توضیح میدن
