### ISSUE TITLE
مشکل در بخش تاریخ شروع کاربر

### ISSUE THREAD

**Issue by FarzadMohtasham** [HamedAp/Ssh-User-management#114]
سلام دوست عزیز
من یه کاربر جدید تعریف کردم ولی تاریخ شروع رو نمیزنه، ممنون میشم بررسی کنی
![Snapshot_230426150544](https://user-images.githubusercontent.com/48632860/234563449-c569c9aa-cd78-47c2-80ad-0d7fde13cd36.jpg)

**Comment by HamedAp** [comment]
با سلام
برای استارت کاربر با اولین کانکشن اون گزینه رو تبدیل کردم .
انشالله با اپدیت جدید اون گزینه حل خواهد شد

**Comment by FarzadMohtasham** [comment]
ممنون برادر
