### ISSUE TITLE
Getting an error after updating the panel(Connection failed) 

### ISSUE THREAD

**Issue by mehdinmo** [HamedAp/Ssh-User-management#117]
Hi 

After updating today, I receive this message when entering the panel:

```shell
Connection failed: Access denied for user 'adminuser'@'localhost
``` 

I read the posts related to this problem in the Telegram support group, I saw that you said to run this command to fix the problem:

```shell
mysql -e "drop user adminuser@localhost"
``` 

but the output gives error:

```shell
ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'adminuser'@'localhost'
``` 
What is the solution to this problem?

**Comment by HamedAp** [comment]
دستور نصب رو دوباره بزنین
