### ISSUE TITLE
معرفی برنامه جدید 

### ISSUE THREAD

**Issue by FarzadMohtasham** [HamedAp/Ssh-User-management#118]
سلام دوست عزیز
برنامه خوبی برای ویندوز دارین که تنهایی SSH Tunnel رو روی حالت VPN Mode ران کنه؟
برنامه netmod وصل میشه ولی حالت VPN Mode نداره و به صورت Socks Proxy باید بهش وصل شد که آدمو مجبور میکنه یه برنامه دیگه مثل nekoray هم ران کنه که قاطی میکنن باهم

اگه برنامه خوبی سراغ داری ممنون میشم معرفی کنی، ممنون

**Comment by alirezarz62** [comment]
برنامه netmod به صورت vpn mode هست عزیز در تنظیمات connection mode رو تغییر بدید

**Comment by FarzadMohtasham** [comment]
توی تنظیمات برنامه؟ این برنامه که قسمت تنظیمات نداره، اگه ممکنه با عکس توضیح مختصری بدین، باتشکر

**Comment by FarzadMohtasham** [comment]
تنظیماتش رو گذاشتم روی VPN Mode ولی اصلا کار نمیکنه و فقط روی 127.0.0.1:1080 میشه بهش وصل شد!!

**Comment by FarzadMohtasham** [comment]
کمی تنظیماتش رو تغییر دادم و اوکی شد، ولی تنها مشکلی که داره اینه که وای فای لپ‌تاپ میره رو حالت No Internet و گوگل کروم و... کار نمیکنه، فقط تلگرام کار میکنه

**Comment by HamedAp** [comment]
سلام
respite vpn 
این برنامه رو من استفاده می کنم و راضی ام 
تست کنین
