### ISSUE TITLE
عدم نمایش کاربران آنلاین روی نسخه 2.1

### ISSUE THREAD

**Issue by fsh230** [HamedAp/Ssh-User-management#12]
سلام ممنون از برنامه خوبت و انتشار آن
مشکلی که دارم روی سرور سیستم عامل ubuntu نسخه 22 نصب جدید کردم کاربران آنلاین را نشان نمی دهد
با تشکر

**Comment by HamedAp** [comment]
پورت تون ۲۲ پیش فرض هستش ؟

**Comment by fsh230** [comment]
> پورت تون ۲۲ پیش فرض هستش ؟

بله از پورت 22 استفاده می کنم

**Comment by HamedAp** [comment]
فایل 
/etc/ssh/sshd_config
رو باز کنین و خط 
#Port 22 
رو تبدیل کنین به :   
Port 22

بعد دوباره از اول دستور نصب رو بزنین .

**Comment by fsh230** [comment]
> فایل /etc/ssh/sshd_config رو باز کنین و خط #Port 22 رو تبدیل کنین به : Port 22
> 
> بعد دوباره از اول دستور نصب رو بزنین .

مشکل حل شد تشکر
