### ISSUE TITLE
محدودیت کاربرها چطور اعمال میشه؟

### ISSUE THREAD

**Issue by cr4zyfish** [HamedAp/Ssh-User-management#121]
سلام
این پروژه اوپن سورس نیست

می خواستم بدونم محدودیت کاربرها چطوری کار می کنه میشه توضیح بدین. چطوری محدودیت ترافیک ایجاد میشه؟

**Comment by HamedAp** [comment]
سلام .
به خاطر دزد ها و کپی برداران اوپن سورس نیست .
محدودیت کاربر هر ثانیه چک میکشه اگر دو نفر وصل باشن کیک میکنه .
ترافیک هم با استفاده از یه سری برنامه ها انجام میشه

**Comment by cr4zyfish** [comment]
فکر کنم زیاد دقیق نیست چون من یک کاربر با محدودیت 50 مگ ایجاد کردم ولی بعد از حدود 90 مگ استفاده قطع شد.
