### ISSUE TITLE
هزینه پنل و استفاده از کانکشن جدید

### ISSUE THREAD

**Issue by Aronablade** [HamedAp/Ssh-User-management#128]
با سلام چند سوال داشتم اول اینکه لایسنس پنل شما چطوری هستش؟  یعنی برای هر سرور هست؟  اگه بخوایم روی چند سروز نصب کنم باید برای هر کدوم مبلغ پرداخت کنم؟  و اینکه لایسنس بصورت سزیال هستش؟  و اگه یه موقع بخوام سرور رو عوض کنم یا ببرم جای دیگه چطور میشه؟ 

بعد اینکه تو پنل شما امکان استفاده از ایپی ۶ هست؟  چون الان روی گوشی های ایفون و همچنین سیمکارت همراه متاسفانه نمیشه ایپی ۶ رو فعال کرد،  اصلا ممکن هست همچین قابلیتی باشه که این دوتا هم با ایپی ۶ وصل بشن؟  یعنی کاربران در هر صورت با ایپی ۶ وصل بشن؟

**Comment by HamedAp** [comment]
سلام 
برای هر پنل نسخه حرفه ای بله لایسنس میخواد .
قابل انتقال هستش و مادام العمر .
میتونین هم 4 استفاده کنین هم ای پی 4

**Comment by nikoobj** [comment]
هزینه لایسنس ؟
