### ISSUE TITLE
پيشنهاد

### ISSUE THREAD

**Issue by Amirmahdiphp** [HamedAp/Ssh-User-management#13]
داداش كارت بيسته ايول
 لطفا سريع آپديت كن محدوديت گيگ و كاربر رو ...

**Comment by HamedAp** [comment]
> داداش كارت بيسته ايول لطفا سريع آپديت كن محدوديت گيگ و كاربر رو ...

انشالله یکی دو روزه حل میشه

**Comment by Amirmahdiphp** [comment]
عزیز منتظریم 😁 میگما نسخه دولوپر نداری که سریع تر بگیرمش؟ (هر یک ساعت دترم صفحه رو رفرش می کنم)
میگما آیدی تلگرامت رو میدی؟

**Comment by HamedAp** [comment]
یه سری کار پیش اومده . انشالله به زودی اپدیت میزنم .

**Comment by HamedAp** [comment]
> حامد جان مرسی از وقتی که برای این برنامه گذاشتی.

خواهش میکنم . 
چند روز درگیر مساله شخصی هستم انشالله به زودی اپدیت جدید خواهیم داشت .

**Comment by mimghaf85** [comment]
بی صبرانه منتظر آپدیت جدید هستیم، جوری که روزی چند بار این صفحه رو رفرش می کنیم :)))
