### ISSUE TITLE
ionCube

### ISSUE THREAD

**Issue by ramindoroozeh** [HamedAp/Ssh-User-management#131]
Script error: the [ionCube](https://www.ioncube.com/) Loader for PHP needs to be installed. The ionCube Loader is the industry standard PHP extension for running protected PHP code, and can usually be added easily to a PHP installation. For Loaders please visit [get-loader.ioncube.com](https://get-loader.ioncube.com/) and for an instructional video please see http://ioncu.be/LV

How to Fix it

**Comment by HamedAp** [comment]
apt remove php* -y

بعد دستور نصب پنل .

**Comment by ramindoroozeh** [comment]
زدم ولی فرقی نکرد

**Comment by firstboy000** [comment]
https://github.com/HamedAp/Ssh-User-management/issues/127#issuecomment-1547003065
شاید کمکت کنه

**Comment by HamedAp** [comment]
`php -v `
بزنین بعد اگر ورژن 8.1 نبود حذف کنین 
`apt remove php7.4`
دستور بالا ورژن 7.4 رو حذف می کنه
