### ISSUE TITLE
خطای 404

### ISSUE THREAD

**Issue by smahmoodh** [HamedAp/Ssh-User-management#132]
درود
بعد از نصب پنل روی هر 3 نسخه 18، 20 و 22 ubuntu روی هر 3 خطای 404 میگیرم و پنل باز نمیشه.
هیچ خطایی هم موقع نصب نمیگیرم و کامل نصب میشه و آدرس پنل رو نشون میده ولی وقتی آدرس رو میزنم 404 میگیرم

`Not Found`
`The requested URL was not found on this server.`
` `
`Apache/2.4.52 (Ubuntu) Server at ***.***.***.*** Port 80`

آیپی رو * گذاشتم

**Comment by HamedAp** [comment]
با سلام . 
با توجه به اینکه شما از پنل های دزدی و کپی استفاده کردین . باید همه اطلاعات اون پنل هارو کاملا حذف کنین و بعد دستور نصب بزنین . 
برای این کار دستور زیر را بزنید :

```
apt purge apache2 -y
apt autoremove -y 
```
