### ISSUE TITLE
تغییر پورت UDPGW

### ISSUE THREAD

**Issue by firstboy000** [HamedAp/Ssh-User-management#133]
> اسکریپت تماس توی سورس ها هستش .
> بزنین پورت 7301 رو فعال می کنه واستون
> 
> _Originally posted by @HamedAp in https://github.com/HamedAp/Ssh-User-management/issues/126#issuecomment-1546351667_

            
با توجه به گفته بالا پورت 7301 برای تماس تصویری و UDP گذاشته میشه که توی سورس من ندیدم
از اونجایی که نت مود امکان تغییر پورت نداره(ندیدم متاسفانه اگر قابل تنظیم هست ممنون میشم راهنمایی کنید) نیاز میشه که تغییرش بدیم به پورت 7300
ممنون میشم راهنمایی کنید.

**Comment by HamedAp** [comment]
سلام وقت بخیر . 
دستور زیر رو بزنین . ازتون پورت میپرسه .

`bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/ssh-calls.sh --ipv4)`
