### ISSUE TITLE
مولتی سرور 

### ISSUE THREAD

**Issue by rezaziyai** [HamedAp/Ssh-User-management#134]
سلام من سوال داشتم ک مولتی سرور به چ صورت عمل میکنه یه توضیح بفرمایید

**Comment by HamedAp** [comment]
آموزش مولتی سرور :

شما دو تا سرور دارید :
سرور اصلی ( پنل روش نصبه و کاربرا توش هستن ) 
سرور دوم هیچ پنلی روش نصب نیست و خام هستش . 

تنظیمات سرور اصلی : 
قسمت تنظیمات api ، یه توکن میسازید !

تنظیمات سرور دوم : 
دستور نصب زیر رو میزنین : 
bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/addserver.sh --ipv4)
ازتون ۲ تا سوال میپرسه ! 
اول ای پی سرور اصلی ! 
دوم توکن 
بعد نصب می کنه و تمام . 

حالا شما یه یوزر داری رو سرور اصلی به نام hamed ! 
میتونی با مشخصات زیر وصل شی به دنیای مجازی بدون فیلتر : 
ip : server1
port : port server1 
user : hamed
pass : ap
——————————
و همین طور با این مشخصات هم میتونی وصل شی : 
ip : server2
port: port server 2 
user : hamed
pass : ap

**Comment by ramindoroozeh** [comment]
این مورد فقط تو نسخه حرفه ای فعال هست؟
من نمیتونم پرداخت ریالی انجام بدم
