### ISSUE TITLE
نصب نسخه قدیمی 

### ISSUE THREAD

**Issue by daBigJay** [HamedAp/Ssh-User-management#135]
روز بخیر 
چطور میشه نسخه 5.0 رو نصب کرد؟

**Comment by HamedAp** [comment]
سلام . 
اصلا پیشنهاد نمیشه . 
اپدیت 5.2 رو بزنین بدون مشکل هستش

**Comment by ali101224** [comment]
> سلام . اصلا پیشنهاد نمیشه . اپدیت 5.2 رو بزنین بدون مشکل هستش

درود 
من اپدیت کردم دیگه پنل باز نمیشه 
This site can’t be reached میشه
البته ssl هم نصب کردم با کد خودتون ولی ربطی نداره فک کنم.
