### ISSUE TITLE
بالا نیامدن پنل بعد از نصب

### ISSUE THREAD

**Issue by mohabatravan** [HamedAp/Ssh-User-management#141]
با سلام و احترام
بعد از نصب پنل به صورت کد میاد بالا

**Comment by HamedAp** [comment]
apt remove php* php7* -y
apt autoremove -y 
این دستور هارو بزنین . 
بعد دستور نصب بزنین . مشکل حل میشه

**Comment by mohabatravan** [comment]
متاسفانه تغییری رخ نداد

**Comment by amirmalakie** [comment]
من هم همین مشکل رو دارم

**Comment by mohabatravan** [comment]
چرا میبندید وقتی مشکل رو حل نکردید؟

**Comment by HamedAp** [comment]
راه حل این مورد فقط حذف php های قدیمی هستش که با دستور بالا حذف میشه و دستور نصب رو دوباره بزنین درست میشه

**Comment by HamedAp** [comment]
> چرا میبندید وقتی مشکل رو حل نکردید؟

حل شد مشکلتون ؟
