### ISSUE TITLE
Remove ssl

### ISSUE THREAD

**Issue by Kamran008a** [HamedAp/Ssh-User-management#143]
کامند حذف ssl رو میخواستم
فکر کنم ۴۴۳ رو اشغال کرده بخاطر اون پورت پنل v2 ام نمیره رو ۴۴۳

**Comment by HamedAp** [comment]
rm -fr /etc/apache2/conf-available/ssl-params.conf 
rm -fr /etc/apache2/sites-available/default-ssl.conf

این دو تا فایل رو حذف کنین مشکل حل میشه
