### ISSUE TITLE
بالا نیومدن پنل بعد از لاگین

### ISSUE THREAD

**Issue by sohrabp72** [HamedAp/Ssh-User-management#144]
بعد از نصب وارد لینک میشم. پنل لاگین باز میشه یوزر و پس رو میزنم میره روی صفحه [http://x.x.x.x/p/login.php](url) و بعدش هیجی نمیاد
خود کروم میزنه:
`This page isn’t working95.164.44.118 is currently unable to handle this request.
HTTP ERROR 500`
دقت کنید که apache این ارور رو نمیده بلکه مرورگر این پیام رو نشون میده

**Comment by HamedAp** [comment]
دستور 
php /var/www/html/p/index.php 

را بزنید و خطا رو ارسال کنین تا راهنمایی کنم

**Comment by sohrabp72** [comment]
```
php /var/www/html/p/index.php
PHP Warning:  Undefined array key "username" in /var/www/html/p/header.php on line 0
```

**Comment by HamedAp** [comment]
دستور نصب رو دوباره بزنین . احتمالا کامل نصب نشده

**Comment by sohrabp72** [comment]
چندین باز زدم ولی کارنمیکنه

**Comment by HamedAp** [comment]
php /var/www/html/p/restoretarikh.php

این دستور رو بزنین و ببینین خطا میده ؟
