### ISSUE TITLE
عدم محاسبه ترافیک

### ISSUE THREAD

**Issue by firstboy000** [HamedAp/Ssh-User-management#147]
ترافیک کاربر محاسبه نمیشه علتش چی هست؟
مجموع ترافیک سرور الان 300 گیگ ولی کاربرا 91 گیگ که برای کاربرا تغییر نمیکنه...

**Comment by HamedAp** [comment]
دستور نصب رو دوباره بزنین مشکل حل میشه . احتمالا محاسبه ترافیک کامل نصب نشده

**Comment by firstboy000** [comment]
انجام شد(حتی با حذف دایرکتوری html و همچنین با ریست ترافیک کردن برای کاربر) ولی بعد از دانلود 300 مگابایت ترافیک مصرفی لحاظ نشده چیزی
اطلاعاتی که شاید بتونه تو خطا یابی کمک کنه:
لیست کرانجاب های فعال:
```
* */3 * * * php /var/www/html/p/versioncheck.php >/dev/null 2>&1
* * * * * php /var/www/html/p/expire.php >/dev/null 2>&1
* * * * * php /var/www/html/p/posttraffic.php >/dev/null 2>&1
* * * * * bash /var/www/html/p/killusers.sh >/dev/null 2>&1
```
تو پروسه نصب مربوط به اجرای restoretarikh بعد از چاپ عناوین جداول وارنینگ های زیر دریافت میشه:
```
PHP Warning:  Undefined array key 2 in /var/www/html/p/restoretarikh.php on line 0
PHP Warning:  Undefined array key 3 in /var/www/html/p/restoretarikh.php on line 0
```
و همچنین فایل یا دایرکتوری به اسم tarikh وجود نداره که بخواد به بکاپ ببره یا حذف کنه...
```
cp: cannot stat '/var/www/html/p/tarikh': No such file or directory
```

**Comment by firstboy000** [comment]
شاید مشکل از این باشه که من پورت پیشفرض پنل رو از روی آپاچی تغییر دادم.
با اجرای دستی پست ترافیک رو لوکال داره کار میکنه و پورت پیشفرض 80
```
>> php /var/www/html/p/posttraffic.php
PHP Warning:  file_get_contents(http://127.0.0.1/p/synctraffic.php): Failed to open stream: Connection refused in /var/www/html/p/posttraffic.php on line 0
PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/html/p/posttraffic.php on line 0
```
شاید بهتر باشه که پورت پنل داینامیک بشه 🤔

**Comment by HamedAp** [comment]
نه مشکل از اون نیست . 
تو کرون جاب خط posttraffic رو پاک نکردین که ؟ 
یا سنتوس نیستین که ؟

**Comment by firstboy000** [comment]
اوبونتو هست،
نه همونطور که تو کامنت قبلی میبینید تو لیست کرون جاب های فعال هستش.

**Comment by firstboy000** [comment]
نتیجه آخرین بررسی: پورت 80 رو فعال کردم براش و شمارش مصرف رو شروع کرد. با دو پیشنهادی که دادم طبیعتا میتونه مشکل حل بشه

1- شاید بهتر باشه که پورت پنل داینامیک بشه که برای امنیت بهتر هم هست...
2- بجای دریافت از url ماژول بشه و فانکشن فراخوانی بشه که منسجم تر میشه...
