### ISSUE TITLE
مواردی که میتونه اضافه شه

### ISSUE THREAD

**Issue by behzadti** [HamedAp/Ssh-User-management#15]
1. سیستم مانیتورینگ وضعیت سرور (cpu,ram,incoming,outcoming)
2.پسورد جنریتر رندوم
3.اضافه شدن بک آپ و ریستور کاربران
4.جستجوی کاربران
5.مقدار استفاده شده حجم کاربر
6.جنریتور اطلاعات اتصال کاربر برای کپی مانند:
Host:
Port:
UserName:
Password:
7.امکان تغییر پورت پنل 
پورت 80 برای پنل استفاده شده که نمیشه ssl گرفت.

**Comment by mimghaf85** [comment]
مهمترینش در حال حاضر، بنظر من سهولت در بک آپ و ریستور اطلاعات کاربران هست.

**Comment by Amirmahdiphp** [comment]
از نظر من اضافه کردن کاربر برای پنل هم اضافه کن که فقط یکی نباشه !

**Comment by HamedAp** [comment]
> از نظر من اضافه کردن کاربر برای پنل هم اضافه کن که فقط یکی نباشه !

کاربر ادمین منظورتونه ؟ 🤔

**Comment by Amirmahdiphp** [comment]
> > از نظر من اضافه کردن کاربر برای پنل هم اضافه کن که فقط یکی نباشه !
> 
> کاربر ادمین منظورتونه ؟🤔

دقیقا میشه ؟ کاربر ادیمن اضافه کرد ؟ (هر پنل کابر ادمین کاربر ها متفاوت داشته باشه)

**Comment by HamedAp** [comment]
منظورتون پنلی کاملا جدا و یوزر های جدا و انلاین و پورت جداست ؟ امکانش هست ولی اصلا پیشنهاد نمیشه

**Comment by Amirmahdiphp** [comment]
اره چرا پیشنهاد نمیشه (البته پنل جدا نه همون پنل باشه ولی با یک نام کاربری و رمز جدا...) امکانش هست ؟

**Comment by Amirmahdiphp** [comment]
آپدیت جدید در چه حاله انشالله تا شند ساعت دیگه در دسترس هست ؟

**Comment by HamedAp** [comment]
اون پنلی که شما میفرمایید آخرین کاری هستش که میشه کرد ! چون احتمال کانفلیکت شدن خیلی بالاست . 
انشالله بتونم امشب بکاپ رو درست می کنم

**Comment by behzadti** [comment]
> اون پنلی که شما میفرمایید آخرین کاری هستش که میشه کرد ! چون احتمال کانفلیکت شدن خیلی بالاست . انشالله بتونم امشب بکاپ رو درست می کنم

مهندس در قسمت تنظیمات بزارین اینجوری خوشگلتره

**Comment by behzadti** [comment]
ممنون ازتون بابت آپدیت 2.2
1.بکاپ و ریستور کاربران در قسمت تنظیمات میتونه قرار بگیره و تب جدا نیاز نیس به نظرم.
2.بکاپ قابلیت دانلود و ریستور قابلیت آپلود داشته باشه.
3.قسمت اطلاعات سرور میتونه در صفحه اصلی قرار بگیره
4.کاربران میتونه در تب جدایی قرار بگیره

**Comment by akhondgav** [comment]
ضمن تشکر از پنل بسیار عالی تون بنده هم نظرم اینه :
- اگر بشه برای قسمت ریستور کردن آپلود هم فایل بک آپ هم اضافه کرد خیلی بهتر هست چون در زمان هایی که سرور جابجا بشه خیلی راحت جابجایی صورت خواهد گرفت.
- قسمت تایمینگ یوزر جدید امکان محدودیت حجم و زمان مشخص ( یک ماهه - سه ماهه  و..... ) خیلی بهتر هست 
- تغییر پورت از همون پنل انجام بگیره خیلی بهتره
- جستجوی کاربر به نظرم جالب میاد
- امکان اسکن QR  برای جنریت یوزر هم اضافه بشه راحت تر میشه

**Comment by Amirmahdiphp** [comment]
1.داداش میشه چند تا پورت ssh داشت ؟
2.میشه TLS زد به SSH?

**Comment by HamedAp** [comment]
> 1.داداش میشه چند تا پورت ssh داشت ؟ 2.میشه TLS زد به SSH?

میشه چند تا پورت داشت ولی با پنل کار نمی کنه فعلا !
مورد 2 رو در اینده اضافه می کنم .

**Comment by HamedAp** [comment]
> ضمن تشکر از پنل بسیار عالی تون بنده هم نظرم اینه :
> 
> * اگر بشه برای قسمت ریستور کردن آپلود هم فایل بک آپ هم اضافه کرد خیلی بهتر هست چون در زمان هایی که سرور جابجا بشه خیلی راحت جابجایی صورت خواهد گرفت.
> * قسمت تایمینگ یوزر جدید امکان محدودیت حجم و زمان مشخص ( یک ماهه - سه ماهه  و..... ) خیلی بهتر هست
> * تغییر پورت از همون پنل انجام بگیره خیلی بهتره
> * جستجوی کاربر به نظرم جالب میاد
> * امکان اسکن QR  برای جنریت یوزر هم اضافه بشه راحت تر میشه

مورد اول حل شده و تو اپدیت بعدی ( احتمالا امشب ) اضافه میشه 
مورد دوم منظورتون رو نفهمیدم ! منظورتون اکانت های یک ماهه و ایناست ؟  قبلا داشتیم همه گفتن تاریخ باشه بهتره ! 
تغییر پورت از پنل تو قسمت تنظیمات انجام میشه ولی احتمالا باگ داره رو بعضی سیستم ها . 
جستجوی کاربر هم اضافه میشه انشالله به زودی 
در مورد QR کد هم باید من یه نمونه ببینم تا بتونم تو پنل اضافه کنم ! نمونه دارید ؟ لینک یا QR ؟

**Comment by behzadti** [comment]
> > ضمن تشکر از پنل بسیار عالی تون بنده هم نظرم اینه :
> > 
> > * اگر بشه برای قسمت ریستور کردن آپلود هم فایل بک آپ هم اضافه کرد خیلی بهتر هست چون در زمان هایی که سرور جابجا بشه خیلی راحت جابجایی صورت خواهد گرفت.
> > * قسمت تایمینگ یوزر جدید امکان محدودیت حجم و زمان مشخص ( یک ماهه - سه ماهه  و..... ) خیلی بهتر هست
> > * تغییر پورت از همون پنل انجام بگیره خیلی بهتره
> > * جستجوی کاربر به نظرم جالب میاد
> > * امکان اسکن QR  برای جنریت یوزر هم اضافه بشه راحت تر میشه
> 
> مورد اول حل شده و تو اپدیت بعدی ( احتمالا امشب ) اضافه میشه مورد دوم منظورتون رو نفهمیدم ! منظورتون اکانت های یک ماهه و ایناست ؟ قبلا داشتیم همه گفتن تاریخ باشه بهتره ! تغییر پورت از پنل تو قسمت تنظیمات انجام میشه ولی احتمالا باگ داره رو بعضی سیستم ها . جستجوی کاربر هم اضافه میشه انشالله به زودی در مورد QR کد هم باید من یه نمونه ببینم تا بتونم تو پنل اضافه کنم ! نمونه دارید ؟ لینک یا QR ؟

به‌ نظرم qr لینک sagernet بزنیم کارآمد تره چون qr عملا فقط رو
ساگرنت فعلا عملی میشه

**Comment by behzadti** [comment]
> > > > ضمن تشکر از پنل بسیار عالی تون بنده هم نظرم اینه :
> > > > 
> > > > * اگر بشه برای قسمت ریستور کردن آپلود هم فایل بک آپ هم اضافه کرد خیلی بهتر هست چون در زمان هایی که سرور جابجا بشه خیلی راحت جابجایی صورت خواهد گرفت.
> > > > * قسمت تایمینگ یوزر جدید امکان محدودیت حجم و زمان مشخص ( یک ماهه - سه ماهه  و..... ) خیلی بهتر هست
> > > > * تغییر پورت از همون پنل انجام بگیره خیلی بهتره
> > > > * جستجوی کاربر به نظرم جالب میاد
> > > > * امکان اسکن QR  برای جنریت یوزر هم اضافه بشه راحت تر میشه
> > > 
> > > 
> > > مورد اول حل شده و تو اپدیت بعدی ( احتمالا امشب ) اضافه میشه مورد دوم منظورتون رو نفهمیدم ! منظورتون اکانت های یک ماهه و ایناست ؟ قبلا داشتیم همه گفتن تاریخ باشه بهتره ! تغییر پورت از پنل تو قسمت تنظیمات انجام میشه ولی احتمالا باگ داره رو بعضی سیستم ها . جستجوی کاربر هم اضافه میشه انشالله به زودی در مورد QR کد هم باید من یه نمونه ببینم تا بتونم تو پنل اضافه کنم ! نمونه دارید ؟ لینک یا QR ؟
> > 
> > 
> > به‌ نظرم qr لینک sagernet بزنیم کارآمد تره چون qr عملا فقط رو ساگرنت فعلا عملی میشه
> 
> NapsternetV نداره ؟ یه تحقیق کنید شاید بشه کاری کرد

من دسترسی به ios ندارم 
ولی ذاتا چون ساگرنت qr یا لینک تولید میکنه فعلا دسترسه به نظرم میتونه اعمال بشه
ولی تو Napsternet V لینک یا QR تولید نمیشه که بشه دیکودش کرد

**Comment by HamedAp** [comment]
> > > > > ضمن تشکر از پنل بسیار عالی تون بنده هم نظرم اینه :
> > > > > 
> > > > > * اگر بشه برای قسمت ریستور کردن آپلود هم فایل بک آپ هم اضافه کرد خیلی بهتر هست چون در زمان هایی که سرور جابجا بشه خیلی راحت جابجایی صورت خواهد گرفت.
> > > > > * قسمت تایمینگ یوزر جدید امکان محدودیت حجم و زمان مشخص ( یک ماهه - سه ماهه  و..... ) خیلی بهتر هست
> > > > > * تغییر پورت از همون پنل انجام بگیره خیلی بهتره
> > > > > * جستجوی کاربر به نظرم جالب میاد
> > > > > * امکان اسکن QR  برای جنریت یوزر هم اضافه بشه راحت تر میشه
> > > > 
> > > > 
> > > > مورد اول حل شده و تو اپدیت بعدی ( احتمالا امشب ) اضافه میشه مورد دوم منظورتون رو نفهمیدم ! منظورتون اکانت های یک ماهه و ایناست ؟ قبلا داشتیم همه گفتن تاریخ باشه بهتره ! تغییر پورت از پنل تو قسمت تنظیمات انجام میشه ولی احتمالا باگ داره رو بعضی سیستم ها . جستجوی کاربر هم اضافه میشه انشالله به زودی در مورد QR کد هم باید من یه نمونه ببینم تا بتونم تو پنل اضافه کنم ! نمونه دارید ؟ لینک یا QR ؟
> > > 
> > > 
> > > به‌ نظرم qr لینک sagernet بزنیم کارآمد تره چون qr عملا فقط رو ساگرنت فعلا عملی میشه
> > 
> > 
> > NapsternetV نداره ؟ یه تحقیق کنید شاید بشه کاری کرد
> 
> من دسترسی به ios ندارم ولی ذاتا چون ساگرنت qr یا لینک تولید میکنه فعلا دسترسه به نظرم میتونه اعمال بشه ولی تو Napsternet V لینک یا QR تولید نمیشه که بشه دیکودش کرد

اندروید هم داره napsternet رو

**Comment by behzadti** [comment]
> 

فقط به صورت فایل inpv شیر میشه

**Comment by mimghaf85** [comment]
نه متاسفانه NapsternetV امکان اسکن QR کد برای SSH رو نداره، فقط برای V2ray امکانپذیر هست.
اپلیکیشن sagerNet و Matsuri هر دو امکان ایمپورت و اکسپورت SSH config رو بصورت لینک دارند. البته این دو اپلیکیشن بیشتر برای v2ray مناسب هستند تا ssh

**Comment by kazemim99** [comment]
بهتره هم user generator پیش فرض داشته باشه هم password generator یوزر رو میتونه مثلا اینطوری باشه user-1 , user-2 تا اگر کاربر خواست عوضش بکنه کار با datepicker هم سخته میشه یه سری check box بصورت پیش فرض مثل 1 روزه (برای تست) , 1 ماهه , 3 ماهه و 6 ماهه قرار داده باشه زیر Datepicker بشه انتخاب کرد , 
همچنین بهتره یه دکمه کپی هم قرار داده بشه یوزر پسوورد کپی کنه 
امکان تعریف سرور هم بهتره باشه تا برای هر سرور یه پنل جدا داشته باشی
فراموشی رمز عبور هم نداریم
در ضمن من الان پنل رو اپدیت کردم کلا یه صفحه سفید اومده هرکاری میکنم درست نمیشه حالا فرض کن من 500 تا کاربر توش ثبت کرده باشم چیکار باید بکنم دسترسی هم ندارم بک آپ بگیرم

**Comment by farshad00419** [comment]
> بهتره هم user generator پیش فرض داشته باشه هم password generator یوزر رو میتونه مثلا اینطوری باشه user-1 , user-2 تا اگر کاربر خواست عوضش بکنه کار با datepicker هم سخته میشه یه سری check box بصورت پیش فرض مثل 1 روزه (برای تست) , 1 ماهه , 3 ماهه و 6 ماهه قرار داده باشه زیر Datepicker بشه انتخاب کرد , همچنین بهتره یه دکمه کپی هم قرار داده بشه یوزر پسوورد کپی کنه امکان تعریف سرور هم بهتره باشه تا برای هر سرور نخوای یه پنل جدا داشته باشی فراموشی رمز عبور هم نداریم در ضمن من الان پنل رو اپدیت کردم کلا یه صفحه سفید اومده هرکاری میکنم درست نمیشه حالا فرض کن من 500 تا کاربر توش ثبت کرده باشم چیکار باید بکنم دسترسی هم ندارم بک آپ بگیرم

mysql -u root -p
show databases;
use پایگاه داده مورد نظر 
show tables;
جدول مربوط به پروژه میاد
اگه خوستی بکاپ بگیری از دستور زیر استفاده کن
mysqldump -u root -p نام پایگاه داده مورد نظر > database_backup_file.sql

و برای بازگردانی پایگاه داده از دستور زیر استفاده کن
mysql -u root -p اسم پایگاه داده < /path/to/file.sql

**Comment by HamedAp** [comment]
> > بهتره هم user generator پیش فرض داشته باشه هم password generator یوزر رو میتونه مثلا اینطوری باشه user-1 , user-2 تا اگر کاربر خواست عوضش بکنه کار با datepicker هم سخته میشه یه سری check box بصورت پیش فرض مثل 1 روزه (برای تست) , 1 ماهه , 3 ماهه و 6 ماهه قرار داده باشه زیر Datepicker بشه انتخاب کرد , همچنین بهتره یه دکمه کپی هم قرار داده بشه یوزر پسوورد کپی کنه امکان تعریف سرور هم بهتره باشه تا برای هر سرور نخوای یه پنل جدا داشته باشی فراموشی رمز عبور هم نداریم در ضمن من الان پنل رو اپدیت کردم کلا یه صفحه سفید اومده هرکاری میکنم درست نمیشه حالا فرض کن من 500 تا کاربر توش ثبت کرده باشم چیکار باید بکنم دسترسی هم ندارم بک آپ بگیرم
> 
> mysql -u root -p show databases; use پایگاه داده مورد نظر show tables; جدول مربوط به پروژه میاد اگه خوستی بکاپ بگیری از دستور زیر استفاده کن mysqldump -u root -p نام پایگاه داده مورد نظر > database_backup_file.sql
> 
> و برای بازگردانی پایگاه داده از دستور زیر استفاده کن mysql -u root -p اسم پایگاه داده < /path/to/file.sql

مرسی از توضیحات ولی همه این ها توی پنل با یه کلیک انجام میشه ! نمیدونم چرا ایشون گفتن بکاپ گیری !

**Comment by kazemim99** [comment]
> 



> الان متوجه شدم ممنون از توضیحاتت
