### ISSUE TITLE
مشکل رمز عبور

### ISSUE THREAD

**Issue by bbehnam007** [HamedAp/Ssh-User-management#150]
بعد از آپدیت وقتی داخل رمز عبورم حروف کپتال باشه کلا وارد نمیشه...چه بزرگ چه کوچیک

**Comment by HamedAp** [comment]
سلام به خاطر تدابیر امنیتی بود که حروف بزرگ در اپدیت بعدی اضافه میشه . 
ولی علامت نمیتونین بزنین . پیشنهاد میشه اگر علامت دارید رمزتون رو عوض کنین
