### ISSUE TITLE
پورت این پنل چیه؟

### ISSUE THREAD

**Issue by ShayanAtaei** [HamedAp/Ssh-User-management#155]
سلام

من روی سرورم فایروال نصب کردم، ممنون میشم بفرمایید این سرویس رو چه پورتی اجرا میشه تا اون رو آزاد بذارم.

**Comment by HamedAp** [comment]
پورت 80 استفاده میشه . 
پیش فرض اپاچی

**Comment by ShayanAtaei** [comment]
> پورت 80 استفاده میشه . پیش فرض اپاچی

ممنونم از شما
سوال دیگرم این هست که کدنویسی برنامه مشکل امنیتی و ddos نداره؟

**Comment by HamedAp** [comment]
همه باگ های امنیتی پنل یک ماه پیش رفع شده .
