### ISSUE TITLE
مشکل نام کاربری و رمز عبور

### ISSUE THREAD

**Issue by FarzadMohtasham** [HamedAp/Ssh-User-management#157]
بعد آپدیت پنل به آخرین نسخه دیگه نمیتونم با همون نام کاربری و رمز عبور قبلی وارد پنل بشم و خطا میده که نام کاربری و رمز عبور اشتباهه، چطوری رمز و نام کاربری پنل رو عوض کنم؟

**Comment by rezareza220** [comment]
mysql -e "drop user admin@localhost;"


بجای admin از یوزر پنل استفاده کنید

**Comment by FarzadMohtasham** [comment]
متاسفانه این مشکل رو حل نکرد و بنده فعلا نمیتونم وارد پنلم بشم

**Comment by firstboy000** [comment]
با راهنمایی دوستمون شما یوزر ارتباطی با دیتابیس رو پاک کردید فکر کنم. که باید ایجاد بشه مجددا.
نوع رمزی که داشتید حروف بزرگ یا کاراکتر داخلش داشت؟
ترجیحا بکاپ ریستور کن به اون تاریخ اگر داری، قبل از آپدیت رمزت رو تغییر بده به ترکیب حروف کوچک و عدد بعد اقدام کن

اگر اطلاعاتی ندارید هنوز داخلش پاک کنید و مجدد نصب کنید.

در غیر اینصورت منتظر باش تا حامدجان خودش راهنماییت کنه

**Comment by rezareza220** [comment]
گر نیاز به ریست یوزر و پسورد ادمین دارید این دستور را زده و دوباره دستور نصب را بزنید :

mysql -e "use ShaHaN;drop table setting;"

**Comment by rezareza220** [comment]
اموزش نصب پنل شاهان :
دستور زیر را در ترمینال خود وارد کرده و یوزر و پسورد ادمین را وارد کنید 

bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/install.sh --ipv4)

جهت آپدیت پنل نیز همان دستور بالا را وارد کرده ( یوزر و پسورد ادمین نیاز نیست - یوزر ها پاک نمی‌شود )

در صورتی که دامنه دارید بعد از دستور نصب ( دقت کنید بعد از دستور نصب ) این دستور را بزنید

bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/ssl.sh --ipv4)

**Comment by rezareza220** [comment]
دوستان عزیز و گرامی . 
اگر احیانا مشکلی با ورود به پنل داشتین بعد از اپدیت ! 
دو حالت هستش ! 
یا پسوردتون علامت های خاص داره که باید فراموشی رمز بزنین و بدون علامت رمز بزارید ! ( جهت هک نشدن پنل )

یا حروف بزرگ و کوچیک یوزر و پسورد رعایت نشده

**Comment by rezareza220** [comment]
دوستانی که بعد از نصب خطای کد های PHP میاره واسشون .
چون ورژن Php شما قدیمی هستش باید ورژن های قدیمی رو پاک کنین و جدید رو نصب کنین  

apt remove php7* php8* php* -y 

بزنین بعد دستور نصب بزنین .

**Comment by rezareza220** [comment]
دوستانی که موقع نصب ارور Not Found میده واستون ! 
چون قبلا پنل های دیگه نصب کردین باید اطلاعات اونارو پاک کنین تا بتونین شاهان رو نصب کنین 

apt purge apache2 -y 
apt autoremove -y 

به ترتیب بزنین و بعدش دستور نصب بزنین .

**Comment by FarzadMohtasham** [comment]
ممنون از آقا رضا و بقیه دوستان بابت راهنمایی، و همچنین آقای حامد عزیز، مشکل دستور 
mysql -e "use ShaHaN;drop table setting;"
و نصب مجددا پنل حل شد، باتشکر
