### ISSUE TITLE
بعد از بارگزاری بک آپ دیگه نمیشه وارد ادمین پنل شد

### ISSUE THREAD

**Issue by hellomynameismoney** [HamedAp/Ssh-User-management#158]
بعد از بارگزاری بک آپ دیگه نمیشه وارد ادمین پنل شد.میگه یوزرنیم یا پسورد اشتباه هست.

**Comment by rezareza220** [comment]
اگر نیاز به ریست یوزر و پسورد ادمین دارید این دستور را زده و دوباره دستور نصب را بزنید :

mysql -e "use ShaHaN;drop table setting;"

**Comment by hellomynameismoney** [comment]
بله مشکل رو رفع کردم.ممنون
