### ISSUE TITLE
لاگین نشدن به پنل

### ISSUE THREAD

**Issue by farshida4** [HamedAp/Ssh-User-management#159]
با عرض سلام و خسته نباشید
من تازه پنل رو نصب کردم و متاسفانه نمیتونم ورود بزنم به پنل

**Comment by HamedAp** [comment]
با سلام 
چه خطایی میده ؟

**Comment by bbehnam007** [comment]
User Panel : YOUR-IP/user/login.php
صفحه لاگین عوض شده

**Comment by Zo0oX** [comment]
برای من هم همینه
