### ISSUE TITLE
فعال نبودن قابلیت تک کاربره

### ISSUE THREAD

**Issue by mimghaf85** [HamedAp/Ssh-User-management#16]
متاسفانه قابلیت تک کاربره کردن در پنل محدودیت رو اجرا نمیکنه و همچنان میشه چندین لاگین همزمان داشت.
روی سرور هم فایل /etc/security/limits.conf رو ویرایش کردم و با دو محدودیت زیر هر کدوم جداگانه تست گرفتم اما باز هم محدودیت فقط یک لاگین همزمان فعال نشد
```
user hard maxlogins 1
user - maxlogins 1
```
دوستان راه حل دیگه ای میتونید پیشنهاد بدید که لااقل روی سرور اعمال بشه کرد؟

**Comment by HamedAp** [comment]
تو قسمت تنطیمات تک کاربره رو فعال کنید . کار میکنه و مشکلی نداره !
وصل میشه ولی هر ۵ ثانیه کیل میکنه !

**Comment by mimghaf85** [comment]
> تو قسمت تنطیمات تک کاربره رو فعال کنید . کار میکنه و مشکلی نداره ! وصل میشه ولی هر ۵ ثانیه کیل میکنه !

متشکرم
پس از kill شدن خودش خودکار مجددا وصل میشه؟ مدت زمان قطعیش چقدر طول میکشه؟
این اتفاق برای هر دو دیوایس میفته یا فقط دیوایس جدید؟

**Comment by HamedAp** [comment]
اولین نفر بر اساس زمان وصل شدن مشکلی نداره ! نفرات بعدی هر ۵ ثانیه قطع میشن . عملا نمیتونن استفاده کنند !

**Comment by mimghaf85** [comment]
جسارتا من این موضوع رو الان در حال تست گرفتن هستم، یک اکانت رو روی ویندوز وصل کردم و همون اکانت رو هم همزمان روی اندروید وصلم
هیچ مشکلی در اتصال نیست و هر دو دیوایس بصورت همزمان بدون قطعی فعال هستند

**Comment by HamedAp** [comment]
تلگرام پیام میدین چک کنیم ؟
Hamed_ap
