### ISSUE TITLE
تماس تصویری

### ISSUE THREAD

**Issue by mehdi7766** [HamedAp/Ssh-User-management#160]
سلام و خسته نباشید
تماس تصویری مشکل داره . پورت هم ۷۳۰۲ قرار میدیم هم موقع نصب و هم داخل تنظیمات گوشی ولی خیلی وقتا کار نمیکنه . شاید از ۱۰۰ تا تماس دوتاش کار کنه .

**Comment by HamedAp** [comment]
سلام . 
طرف مقابل هم باید تماس هاش فعال باشه .
