### ISSUE TITLE
نمایش صفحه سفید به جای پنل

### ISSUE THREAD

**Issue by hosseinsyd997** [HamedAp/Ssh-User-management#162]
سلام و وقت بخیر
من پنل رو نصب کردم و حتی یوزر هم ساختم براش و به خوبی کار میکنه
فقط اینکه صفحه پنل برای من لود نمیشه
طبق گفته ی شما آدرس ورود به پنل با پورت 80 آپاچی به صورت زیر در میاد

http://SERVER_IP/p
ولی توی مسیر فوق فقط یک صفحه سفید خالی لود میشه
![shahan](https://github.com/HamedAp/Ssh-User-management/assets/120299969/a44edaeb-f63c-43d0-bb5e-80e2b4c83baa)

**Comment by HamedAp** [comment]
سلام . احتمالا کامل نصب نشده . دوباره دستور نصب بزنین

**Comment by ArmanKarami** [comment]
با سلام وا حترام پنل رو نصب کردم صفحه صفید با مشخصات زیر میاد چندین بار هم نصب کردم مشکل چیه ؟

http://xxx.xxx.xxx.xxx/p/index.php

<?php //004a4
// 
//    _____ _           _    _       _   _
//   / ____| |         | |  | |     | \ | |
//  | (___ | |__   __ _| |__| | __ _|  \| |
//   \___ \| '_ \ / _` |  __  |/ _` | . ` |
//   ____) | | | | (_| | |  | | (_| | |\  |
//  |_____/|_| |_|\__,_|_|  |_|\__,_|_| \_|
// 
// 
//   _____      _   _      _
//  |  __ \    | \ | |    | |
//  | |__) |_ _|  \| | ___| |
//  |  ___/ _` | . ` |/ _ \ |
//  | |  | (_| | |\  |  __/ |____
//  |_|   \__,_|_| \_|\___|______|
// 
// 
if(extension_loaded('ionCube Loader')){die('The file '.__FILE__." is corrupted.\n");}echo("\nScript error: the ".(($cli=(php_sapi_name()=='cli')) ?'ionCube':'<a href="https://www.ioncube.com">ionCube</a>')." Loader for PHP needs to be installed.\n\nThe ionCube Loader is the industry standard PHP extension for running protected PHP code,\nand can usually be added easily to a PHP installation.\n\nFor Loaders please visit".($cli?":\n\nhttps://get-loader.ioncube.com\n\nFor":' <a href="https://get-loader.ioncube.com">get-loader.ioncube.com</a> and for')." an instructional video please see".($cli?":\n\nhttp://ioncu.be/LV\n\n":' <a href="http://ioncu.be/LV">http://ioncu.be/LV</a> ')."\n\n");exit(199);
?>
HR+cPqrzE9f9p87T5DAikUYp12uf+4ZVZwXJvEEWBiBaaDnmvYQ6NwVhA81Dhi8hIw0cLQ6nxi4b
tHNK3qpA4Ekz0iVtn5t35TD2UYtBqbZ6l23u+Hk+rwbv1rt69roHnVmfJYbSI6U2YsX8zPxKIkpy
QzHVoncYCwswyWxnvD54HOzH6qmorTtdX8KiZOLJ3QT4TL/tIBWPFkP1Fv+vMorZJ9DKhvVehewE
M16ofgHAySvZqC6QIj95FyWeDPWNaa8Edl3LmTGly4h0HU1nqh3qw9cFBOFuRwnmZtXN0/ACrs4v
B1GrKUNxSyZ2i4m2G8Zvh8dgf7cg00XIOGuNC7eUD1xPfJ7IggEGXTI20DVA6vRv5sd74+rMjw56
bSZCcp8N3JBJMIo8/5KjgB092ESjmbNHBDFpNkQAbaOEBX3xJ9j5AlsAu1zn+E12E7C8q9yNJEFH
g463v3Z/tS6hSVVq7Afso9ilifxTZoP9JQrZoWXCj0JNcNxmOKaDOjD3iYlwb8rRIbO0j9HCyPP4
NX3c+QYSC6WSdECbPp9SHB9P/yG3wlj0hoeCAawWBeoMCdu4JKr1vk64Enguc83c9NgSEyai214N
و تا اخر همینطور خطاست

**Comment by bbehnam007** [comment]
User Panel : YOUR-IP/user/login.php
صفحه لاگین عوض شده

**Comment by bbehnam007** [comment]
> سلام . احتمالا کامل نصب نشده . دوباره دستور نصب بزنین
مشکلی که هست وقتی نصب یا آپدیت تموم میشه در پوتی قسمت پنل آدرس هنوز /p/index.php هست که اونم باید عوض بشه

**Comment by bbehnam007** [comment]
قبل نصب حتما رمز دیفالت بزارید
