### ISSUE TITLE
مشکل ورود بعد از نصب

### ISSUE THREAD

**Issue by Abolfazl48** [HamedAp/Ssh-User-management#164]
سلام 
پنل بدون مشکل نصب میشه ولی بعد از نصب با ورود یوزر و پسورد با خطا پسورد اشتباه مواجه میشم.
این نتیجه بعد از نصب هست پسوردی نیست که من وارد کردم و یک خطا هم دیده میشه

Panel Link : http://######/p/index.php
UserName : admin
/dev/fd/63: line 293: printf: `r': invalid format character
Password : vE20@SKN3i
Port : 22

**Comment by mnsb13600** [comment]
من هم این مشکل را دارم و میگه پسورد نامعتبر

**Comment by HamedAp** [comment]
سلام . 
از پسورد بدون علامت استفاده کنین . 
فراموشی رمز بزنین و دوباره رمز جدید بدون علامت بسازید .

`mysql -e "use ShaHaN;drop table setting;"`

**Comment by ethanhanif** [comment]
چطوری password رو ریست کنیم هرکاری می کنم با password ی که ست کردم لاگین نمیشه
