### ISSUE TITLE
cp: cannot create regular file '/usr/local/bin/badvpn-udpgw': Text file busy

### ISSUE THREAD

**Issue by boyitnew** [HamedAp/Ssh-User-management#165]
هنگام اجرا دستور زیر
bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/ssh-calls.sh --ipv4)
ارور میده : 

cp: cannot create regular file '/usr/local/bin/badvpn-udpgw': Text file busy

**Comment by HamedAp** [comment]
یک بار سرور رو ریستارت کنین . 
فایل در حال اجرا هستش که ارور میده
