### ISSUE TITLE
مشکل ورود

### ISSUE THREAD

**Issue by ahmadmit2020** [HamedAp/Ssh-User-management#166]
وقتی یوزرنیم و پسورد رو چه در زمان نصب و چه از پنل تغییر میدیم دیگ وارد نمیشه ، خطایی ام نمایش نمیده

**Comment by HamedAp** [comment]
سلام . صفحه سفید میاد ؟

**Comment by bbehnam007** [comment]
User Panel : YOUR-IP/user/login.php
صفحه لاگین عوض شده

**Comment by HamedAp** [comment]
> User Panel : YOUR-IP/user/login.php صفحه لاگین عوض شده

نه این پنل کاربری هستش
