### ISSUE TITLE
Installing The Panel On DataCenters Like Azure

### ISSUE THREAD

**Issue by jaafar-c** [HamedAp/Ssh-User-management#167]
Hello,
The panel can't be installed on most of my servers of those well-known companies. I hit install after copying your installing command, but I don't find any file being installed in /var/www/html. Is there a way of installing it manually or what do you suggest? 
Appreciate any help
Thanks

**Comment by HamedAp** [comment]
add dns server ( 8.8.8.8 ) to your server

**Comment by jaafar-c** [comment]
There is no such option in LightSail AWS!

**Comment by HamedAp** [comment]
nano /etc/resolv.conf 

Then Add this : 
nameserver 8.8.8.8

save and update panel 
then install panel
