### ISSUE TITLE
حذف پنل

### ISSUE THREAD

**Issue by mousa1586** [HamedAp/Ssh-User-management#168]
با چه دستوری میشه پنل حذف کرد؟
بار اول موقع نصب پورت پرسید 9011 زدم آدرس پنل لود نمیشه
بعد اون چند بار نصب کردم اما پورت نمیپرسه که بخوام تغییر بدم

**Comment by HamedAp** [comment]
سلام . پورتی که میپرسه برای پورت تماس هستش . 
ادرس پنل :  
domain.com/p/index.php

**Comment by mousa1586** [comment]
متاسفانه بالا نمیاد

**Comment by EmadNajafi** [comment]
سلام پنل رو اپدیت کردم دیگه بالا نمیاد چکارش کنم؟
