### ISSUE TITLE
انجام آپدیت و سفید شدن صفحه

### ISSUE THREAD

**Issue by fsh230** [HamedAp/Ssh-User-management#17]
سلام من با نسخه 2.1 کار می کردم که پیغامی مبنی بر انجام آپدیت با دستور روی پنل ظاهر می شد اومدم با پوتی به سرور وصل شدم و دستور رو زدم ازم یوزر و پسورد گرفت مراحل تمام شد الان پنلم سفید میاد

**Comment by fsh230** [comment]
یکبار دیگ دستور آپدیت را اجرا کردم مشکل برطرف گردید

**Comment by fsh230** [comment]
دوباره که نسخه جدید رو انتشار دادی دستور آپدیت رو زدم و صفحه پنلم سفید میاد سرویس آپاچی رو استاپ استارت کردم و چند بار دستور آپدیت رو تکرار کردم متاسفانه مشکلم هم چنان پابرجاست چه کنم مهندس هلپ می.

**Comment by HamedAp** [comment]
امکانش هست عکس بفرستین ؟

**Comment by fsh230** [comment]
این هم از عکس
https://s2.uupload.ir/files/capture_jwod.jpg

**Comment by HamedAp** [comment]
دستور 
systemctl restart mariadb
رو بزنین ببینین درست میشه ؟

**Comment by fsh230** [comment]
این دستور هم زدم متاسفانه درست نشد فکر می کنم این مشکل مربوط به مساله احراز هویت کاربر هم باشه چون من دیروز رمز رو عوض کردم درست شد الان می خوام از طریق ssh  ترمینال رمز رو عوض کنم چگونه این کار رو بکنم ؟

**Comment by HamedAp** [comment]
mysql -e "use ShaHaN; drop table setting;"

این دستور رو بزنین بعد دستور نصب رو بزنین تا رمز رو بخواد

**Comment by fsh230** [comment]
این دستور کل دیتابیس رو پاک می کنه ؟

**Comment by HamedAp** [comment]
نه فقط یوزر و پسورد

**Comment by fsh230** [comment]
طبق فرمایش شما این کار هم انجام شد یوزر و رمز تغییر داده شد با مشخصات جدید وارد شدم دوباره صفحه سفید میاد

**Comment by HamedAp** [comment]
mysql -N -e "use ShaHaN; select adminuser from setting;"

این دستور رو بزنین ببینین واستون یوزر ادمین رو نشون میده ؟

**Comment by fsh230** [comment]
جواب این دستور 
(42S02) at line 1: Table 'ShaHaN.setting' doesn't exist

**Comment by HamedAp** [comment]
تو تلگرام پیام بدین 
hamed_ap
