### ISSUE TITLE
خطای آپدیت در ورژن 5.9

### ISSUE THREAD

**Issue by amirhoseincfs** [HamedAp/Ssh-User-management#170]
سلام وقت بخیر
وقتی به ورژن 5.9 آپدیت می کنیم با خطای مرورگر زیر مواجه میشیم و نمی تونیم به پنل وارد شیم.
This page isn’t working
{MY-IP} is currently unable to handle this request.
HTTP ERROR 500

**Comment by HamedAp** [comment]
دستور زیر رو بزنین و خطا رو بفرستین :

php /var/www/html/p/index.php

**Comment by amirhoseincfs** [comment]
نتیجه دستور خدمت شما:
```
root@MKT-GR1:~# php /var/www/html/p/index.php
PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'amir'@'localhost' (using password: YES) in /var/www/html/p/config.php:12
Stack trace:
#0 /var/www/html/p/config.php(12): mysqli->__construct()
#1 /var/www/html/p/header.php(0): unknown()
#2 /var/www/html/p/index.php(0): unknown()
#3 {main}
  thrown in /var/www/html/p/config.php on line 12
```

**Comment by HamedAp** [comment]
mysql -e "drop user amir@localhost;"

این دستور رو بزنین و بعدش دستور نصب بزنین .
اگر رمزتون علامت داره فراموشی رمز بزنین

**Comment by amirhoseincfs** [comment]
ممنونم ❤️ درست شد.
فقط یه مورد اینکه الان دوباره پنل رو نصب کردیم در گوشه سمت چپ پایین صفحه ورژن 5.9 رو نشون میده ولی روبه روی اون گوشه سمت راست پایین صفحه یک خط قرمز فیکس شده تحت عنوان (لطفا پنل خود را از طریق دستور آپدیت کنید .) ظاهر شده. این مشکلی ایجاد نمیکنه؟!
