### ISSUE TITLE
بعد از اپدیت دیگه پنل بالا نمیاد

### ISSUE THREAD

**Issue by EmadNajafi** [HamedAp/Ssh-User-management#173]
سلام بعد از اپدیت کردن پنل دیگه بالا نمیاد از دستور زیر استفاده کنید

**Comment by EmadNajafi** [comment]
دوستان کسی اگه این مشکل رو دار با وارد دستور زیر و بعد از اون نصب مجدد پنل مشکلش حل میشه 
mysql -e "drop user user-name-planel@localhost;"

**Comment by EmadNajafi** [comment]
mysql -e "drop user panel-user-name@localhost;"

با وارد کردن دستور بالا و نصب مجدد پنل مشکلتون حل میشه

**Comment by ArmanKarami** [comment]
با سلام و احترام
پنل نصب شد و پس از اپدیت مجدد ورژن 5.9 صفحه سفید شد و پنل بالا نیومد . به دستور هم بزارید واسه تغییر پسورد و نام کاربری از طریق کد روی سرور
پسوردم رو قبول نمیکرد اپدیت کردم .

**Comment by EmadNajafi** [comment]
سلام پنل رو پاک کنید دوباره نصب کنید درست میشه

**Comment by EmadNajafi** [comment]
سلام پنل رو مجدد نصب کنید درست میشه

**Comment by ArmanKarami** [comment]
3 بار نصب کردم نشد !!! مجبور شدم هاست ریست کنم

**Comment by bbehnam007** [comment]
User Panel : YOUR-IP/user/login.php
آدرس عوض شده
