### ISSUE TITLE
راهنمای رفع خطای پنل بعد از آپدیت

### ISSUE THREAD

**Issue by jamali-amirhossein** [HamedAp/Ssh-User-management#175]
با سلام و احترام.
دوستان عزیز توجه داشته باشید چند تا نکته توی **نصب و آپدیت** این پنل وجود داره که هم ترتیب های اون باید رعایت بشه ، هم نکات ریز نصب پنل که در زیر ذکر می کنم.

**نصب جدید**
(کسانی که میخوان تازه پنل را نصب کنن و از اون استفاده کنن)

۱. سرور شما باید خام باشه و هیچ گونه نرم افزاری (تاکید میکنم) هیچ نرم افزار دیگه ای خصوصا کنترل پنل های مدیریت هاستینگ و غیره روی سرور شما نصب نباشه.

۲. جهت نصب پنل بهترین کارایی و عملکرد را در ورژن ۲۲ ابونتو خواهید داشت

۳. ترجیحا با دستور زیر قبل از نصب پنل پورت دیفالت SSH تون که روی ۲۲ هست رو دستی تغییر بدید.
دستور:
`sudo nano /etc/ssh/sshd_config`

۴. هنگام وارد کردن دستور نصب پنل از شما یوزرنیم مدیریت و پسورد مدیریت میخواد که برای وارد کردن این دو تا به این نکات توجه کنید: ( یوزرنیم مدیریت حتما با حروف کوچک انگلیسی و بدون کاراکتر اضافی باشد _ پسورد مدیریت را در هنگام نصب از طریق ssh فقط و فقط از حروف کوچک انگلیسی استفاده کنید و پس از نصب کامل پنل از داخل تنظیمات پنل اون پسورد رو تغییر دهید همچنین هیچگاه در پسورد از کاراکتر های نشانه گذاری یا اضافی مانند @-#-$ و … استفاده نکنید )

**آپدیت ورژن جدید**
برای کسانی که پنل را از قبل نصب کردند و میخوان به ورژن جدید آپدیت کنند
(در آپدیت رعایت ترتیب موارد زیر به همین ترتیبی که گفته شده ضروری است) فتح الله بازی و خلاقیت ممنوع 😂

۱. ابتدا از طریق یکی از نرم افزار های اتصال به ssh با یوزر root وارد محیط دستوری ابونتو سرورتون بشید.

۲. یک بار با دستور زیر سرور تون رو اپدیت کنید:
`apt update && apt upgrade -y`

۳. پس از تکمیل اپدیت سرور، دستور نصب شاهان پنل را بزنید تا فرایند آپدیت پنل آغاز شود.
دستور نصب شاهان:
`bash <(curl -Ls https://raw.githubusercontent.com/HamedAp/Ssh-User-management/master/install.sh -
-ipv4)`

۴. پس این که آپدیت انجام شد و اطلاعات ورود به پنل تان را به شما نمایش داد (اصلا عجله نکنید) و اطلاعات رو توی مرورگرتون وارد نکنید چون پنل باز نمیشه و با خطا مواجه میشید (هنوز کار داریم)

۵. با دستور پایگاه داده زیر یک بار یوزرنیم مدیریتی خود را ریست کنید (جای adminuser نام کاربری ورود به پنل خودتان را بذارید)
`mysql -e "drop user adminuser@localhost;"`

۶. دوباره دستور نصب شاهان پنل را وارد کنید و دوباره یوزرنیم و پسورد انتخاب نمایید. (به نکات انتخاب یوزرنیم و پسورد که در بالا در قسمت نصب جدید توضیح داده شد دقت کنید)

۷.(برای اطمینان بیشتر) دوباره دستور نصب ssl هم وارد کنید و دامنه خودتون رو بزنید تا نصب تمام و کمال تکمیل بشه.

۸. یکبار سرور خودتون رو با دستور reboot ری استارت کنید.

و کار تمام است و لذت ببرید ❤️

**Comment by bbehnam007** [comment]
ممنون از راهنمایی دوست عزیز فقط یک راه حل سریع و راحت و ساده....قبل از آپدیت رمز پنل را 123456 (دیفالت) بزارید آپدیت کنید دوباره رمز را بعد از آپدیت تغییر دهید

**Comment by amirhoseincfs** [comment]
> ممنون از راهنمایی دوست عزیز فقط یک راه حل سریع و راحت و ساده....قبل از آپدیت رمز پنل را 123456 (دیفالت) بزارید آپدیت کنید دوباره رمز را بعد از آپدیت تغییر دهید

سپاس از راهنمایی تون دوست من

**Comment by amirhoseincfs** [comment]
> ممنون از راهنمایی دوست عزیز فقط یک راه حل سریع و راحت و ساده....قبل از آپدیت رمز پنل را 123456 (دیفالت) بزارید آپدیت کنید دوباره رمز را بعد از آپدیت تغییر دهید

سپاس از راهنمایی تون دوست من
