### ISSUE TITLE
عوض کردن پورت پیشفرض

### ISSUE THREAD

**Issue by aminos2012** [HamedAp/Ssh-User-management#177]
سلام
من روی سرورم وردپرس نصب کردم
وقتی پنل شاهان رو نصب میکنم برای باز کردنش موقع وارد کردن ادرس پیشفرض پنل، سایتم میاد بالا
میخواستم بدونم چطور میشه پورت پیشفرض پنل شاهان رو عوض کنم که این دوتا باهم تداخل نداشته باشن
ممنون

**Comment by HamedAp** [comment]
لطفا تو گروه تلگرام از دوستان بپرسید  :

https://t.me/+PXC_WxdPE0cyNzZk
