### ISSUE TITLE
لود نشدن پنل

### ISSUE THREAD

**Issue by narmafkar** [HamedAp/Ssh-User-management#178]
سلام وقت بخیر.من دیشب پنل رو خریداری کردم.مشکلی که هست نصب انجام میشه و لاگین میکنم  ولی بعد از حدود 2 دقیقه دیگه پنل لود نمیشه.چند بار ریبیلد کردم مجدد نصب کردم.روی دوتا سرور امتحان کردم.با همراه اول و ایرانسل با vpn و بدن 
vpn هم تست کردم بازهم لود نمیکنه.مشکل چیه؟
فقط هم نسخه حرفه ای اینجوریه نسخه رایگان مشکلی نداره

**Comment by HamedAp** [comment]
سلام . امکانش هست کشور سرورتون رو بفرمایید  ؟
