### ISSUE TITLE
پسورد شامل @ و ! بود دیگه وارد پنل نمیشه

### ISSUE THREAD

**Issue by mkhib** [HamedAp/Ssh-User-management#179]
دستور
`mysql -e "drop user admin@localhost;"`

هم که میزنم وقتی دوباره پنل رو نصب میکنم دیگه ازم یوزر پس نمیگیره و همون یوزر پس قبلی ست شده روش اما حتی کپی میکنم پسورد رو از روی پیغام موفقیت بازم وارد نمیشه

فیلد پسورد اصلا اجازه تایپ کاراکتر های خاص رو نمیده مثل @ و ! میشه کپی پیست کرد اما باز میگه پسورد اشتباه هست.

**Comment by bbehnam007** [comment]
با winncpبروید داخل و فایل config.php را حذف کنید 
در دیتا بیس هم پسورد خودتون رو بزارید 123456......جدول setting
در انتها مجدد نصب کنید درست میشود

**Comment by bbehnam007** [comment]
/var/www/html/p

**Comment by mkhib** [comment]
> با winncpبروید داخل و فایل config.php را حذف کنید در دیتا بیس هم پسورد خودتون رو بزارید 123456......جدول setting در انتها مجدد نصب کنید درست میشود

تو جدول setting ستون adminpassword رو عوض کردم و دوباره `mysql -e "drop user admin@localhost;"` زدم بعد پنل رو نصب کردم درست شد ممنون.

**Comment by sajjadmehdipour** [comment]
> با winncpبروید داخل و فایل config.php را حذف کنید در دیتا بیس هم پسورد خودتون رو بزارید 123456......جدول setting در انتها مجدد نصب کنید درست میشود

با winncp  فایل  config.php  رو پاک کردم ...فقط مسیر دیتابیس کجاست و چطوری تغییرش بدیم ...جدول setting هم کجاست
ممنون
من فقط الان کاربرام دارن از سرور استفاده میکنن و مشکلی ندارن و خودم نمیتونم ورود بکنم پسورد قبلی داخلش @  بوده 

ممنون مبشم کمکم کنید

**Comment by mkhib** [comment]
> > با winncpبروید داخل و فایل config.php را حذف کنید در دیتا بیس هم پسورد خودتون رو بزارید 123456......جدول setting در انتها مجدد نصب کنید درست میشود
> 
> با winncp فایل config.php رو پاک کردم ...فقط مسیر دیتابیس کجاست و چطوری تغییرش بدیم ...جدول setting هم کجاست ممنون من فقط الان کاربرام دارن از سرور استفاده میکنن و مشکلی ندارن و خودم نمیتونم ورود بکنم پسورد قبلی داخلش @ بوده
> 
> ممنون مبشم کمکم کنید

اول این دستور رو بزنین
`mysql -u root -p`
بعد رمز یوزر root رو وارد کنین
بعد با این دستور دیتا بیس شاهان رو انتخاب کنین
`USE ShaHaN;`
بعد با دستور 
`UPDATE setting SET adminpassword=123456;`
رمز ادمین ریست میشه.
