### ISSUE TITLE
#bug استفاده کاربر حتی پس از اتمام زمان

### ISSUE THREAD

**Issue by behzadti** [HamedAp/Ssh-User-management#18]
کاربر حتی پس از اتمام زمان سرویسش میتونه وصل بشه

**Comment by HamedAp** [comment]
اگر امروز تاریخ انقضا باشه امشب ساعت ۱۲:۰۵ دقیقه بامداد غیرفعال میشه . هر شب ساعت ۱۲:۰۵ چک میشه تاریخ انقضا ها

**Comment by behzadti** [comment]
> اگر امروز تاریخ انقضا باشه امشب ساعت ۱۲:۰۵ دقیقه بامداد غیرفعال میشه . هر شب ساعت ۱۲:۰۵ چک میشه تاریخ انقضا ها

در قسمت کاربران غیر فعال هستش و کانکت میباشد

**Comment by HamedAp** [comment]
در اپدیت جدید مشکل حل خواهد شد .
