### ISSUE TITLE
عدم آپدیت

### ISSUE THREAD

**Issue by bbehnam007** [HamedAp/Ssh-User-management#181]
پنل رو آپدیت کردم ولی هنوز میزنه پنل خود را آپدیت کنید و ورژنی که نمایش میده 5.9 هست.

**Comment by bbehnam007** [comment]
دوستانی که لینوکس ایران دارند.......حتما dns های شکن رو ست کنند

**Comment by HamedAp** [comment]
سلام . حل شد مشکل ؟ 
لطفا تو گروه تلگرام از دوستان بپرسید  :

https://t.me/+PXC_WxdPE0cyNzZk

**Comment by bbehnam007** [comment]
بله با استفاده از nameserverشکن مشکل ایرانم حل شد......vps های ایران
