### ISSUE TITLE
ارور بالا نیومدن پنل بعد از نصب

### ISSUE THREAD

**Issue by myrezaj** [HamedAp/Ssh-User-management#183]
سلام وقت بخیر
من بعد از نصب با ارور :
Not Found
The requested URL was not found on this server.

Apache/2.4.41 (Ubuntu) Server at {my ip } Port 80
مواجه میشم ، میشه لطفا راهنمایی کنید ؟
سپاس

**Comment by HamedAp** [comment]
سلام 
apt purge apache2 -y
apt autoremove -y

این دستور رو بزنین به ترتیب و بعد دستور نصب بزنین .
