### ISSUE TITLE
پورت پنل

### ISSUE THREAD

**Issue by m0o0rteza** [HamedAp/Ssh-User-management#184]
سلام وقت بخیر
تا وقتی فایروال فعال هستش پنل بالا نمیاد. بعد از غیرفعال کردن فایروال پنل اوکی میشه. لطفا پورت مربوط به پنل رو اعلام کنید تا فقط اون پورت موردنظر باز بشه. ممنون

**Comment by mosish** [comment]
پورت 80 هست که مربوط به HTTP هست
