### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Kiya6955** [HamedAp/Ssh-User-management#192]
![image](https://github.com/HamedAp/Ssh-User-management/assets/102658999/76cfce5e-8205-4a01-9abc-a1da92d44bef)
چیکارش کنم دوتا سرور خریدم هر دوش اینجوریه
از یه دیتا سنتر دیگه گرفته بودم اوکی بود

**Comment by HamedAp** [comment]
دستور shahan رو بزنین بعد فراموشی رمز

**Comment by Kiya6955** [comment]
نشد ستونم

> دستور shahan رو بزنین بعد فراموشی رمز
