### ISSUE TITLE
پیشنهاد برای آپدیت های بعدی

### ISSUE THREAD

**Issue by irluca** [HamedAp/Ssh-User-management#2]
پیشنهاد میکنم این موارد رو توی آپدیتهای بعدی اضافه کنید:
- تمدید کردن یوزر
-  محدودیت حجم استفاده
-  محدودیت تعداد دستگاهی که میتونه از یک اکانت استفاده کنه.

همچنین با توجه به اینکه آی پی به راحتی بعد از کانکت شدن قابل رصد شدنه؟ برای مخفی کردن آی پی هم یه فکری بکنید.
خیلی ممنونم از زحماتتون

**Comment by kingabsent** [comment]
امکان اتصال چند سرور به یک پنل
امکان ساخت یوزر چند کار بره و تک کاربره
امکان استعالم مقدار ترافیک و روز توسط کاربر
امکان ساخت بسته هایی با معیار روز مثلا 1 ماههه و ..... و حجم 10 گیگ 20 گیگ

**Comment by AzerilWarframe** [comment]
udp over tcp

**Comment by tab2536** [comment]
امکان اتصال چند سرور به یک پنل
امکان ساخت یوزر چند کار بره و تک کاربره
امکان استعالم مقدار ترافیک و روز توسط کاربر
امکان ساخت بسته هایی با معیار روز مثلا 1 ماههه و ..... و حجم 10 گیگ 20 گیگ

**Comment by darklies** [comment]
خروجی فایل کانفیگ لاک شده برای NV چه اندروید چه آیفون

**Comment by Feriyali** [comment]
سلام و خسته نباشید 
واقعا خیلی عالی خب طبیعیه که اول کار ایرادات و مشکلاتی باشه واقعا تشکر به خاطر اشتراک گذاری شما بدون هیچ چشم داشت و تلاش برا ارتقا امیدوارم ایرادات هم رفع بشه فقط خواستم ازتون تشکر کنم به خاطر کاری که به صورت رایگان در خدمت عموم قرار دادین موفق باشین

**Comment by staramid** [comment]
حامد جان سلام . واقها مرسی بابت وقتی که برای این برنامه میزاری. 
من یه سوال داشتم و اینکه ما همون دامنه ای رو قرار میدیم که cdn داره ؟

**Comment by staramid** [comment]
حامد جان امکانش هست صفحه مدیریت تازه سازی اتوماتیک داشته باشه؟

**Comment by HamedAp** [comment]
> حامد جان سلام . واقها مرسی بابت وقتی که برای این برنامه میزاری. من یه سوال داشتم و اینکه ما همون دامنه ای رو قرار میدیم که cdn داره ؟

بله اگر ربات تلگرام میخواین !

**Comment by HamedAp** [comment]
> حامد جان امکانش هست صفحه مدیریت تازه سازی اتوماتیک داشته باشه؟

منظورتون کدوم قسمته ؟

**Comment by staramid** [comment]
> > حامد جان امکانش هست صفحه مدیریت تازه سازی اتوماتیک داشته باشه؟
> 
> منظورتون کدوم قسمته ؟

صفحه اصلی که کاربران آنلاین رو میشه دید.
