### ISSUE TITLE
باز نشدن صفحه بعد از بروزسانی

### ISSUE THREAD

**Issue by kazemim99** [HamedAp/Ssh-User-management#20]
بنده رمز رو عوض و پورت default بردم روی 1027 هر کاری کردم با رمز جدید وارد نشد مجدد برنامه رو نصب کردم اینبار وارد شد ولی هیچ صفحه ای بالا نیومد
![image](https://user-images.githubusercontent.com/14816958/221114092-66e24d67-a780-42c7-bda8-da33ef89311b.png)

**Comment by HamedAp** [comment]
تو همون صفحه ctrl+u بزنین . 
سورس صفحه رو نشون میده . 
اخرین خط ببینین چه خطایی میده

**Comment by Amirmahdiphp** [comment]
برای منم همین ارور اومد بعد دوباره نصب کردم یوزر نیم پسورد رو admin admin گذاشتم درست شد

**Comment by HamedAp** [comment]
> برای منم همین ارور اومد بعد دوباره نصب کردم یوزر نیم پسورد رو admin admin گذاشتم درست شد

احتمالا یوزر و پسورد قبلیتون اون بوده به خاطر اونه !
