### ISSUE TITLE
پیشنهاد 

### ISSUE THREAD

**Issue by Amirmahdiphp** [HamedAp/Ssh-User-management#21]
سلام خسته نباشید میشه وقتی یوزر اضافه می کنیم فایل NapsternetV رو هم بده که دستی وارد نکنیم؟
اگر می خواهید یه نمونه کد بهتون بدم npv4.

**Comment by HamedAp** [comment]
سلام .
بفرستین .
انکود شده هستش احتمالا !

**Comment by HamedAp** [comment]
باید بررسی بشه .
