### ISSUE TITLE
SSL for web page

### ISSUE THREAD

**Issue by OpiranClub** [HamedAp/Ssh-User-management#22]
hi
good panel

put auto ssl on the next update to resolve with dns and https and add some protocle such as squid, tls/ssh, sslh, badvpn and etc

by the way its nice

**Comment by OpiranClub** [comment]
بات تلگرام هم توی نمونه های پرتغالی زبان زیاد دیدم برای ایده گرفتن اگه خواستی بگو برات بفرستم و یه چیز دیگه محدودیت ترافیک چجوری میخوای اعمال میکنی؟

**Comment by OpiranClub** [comment]
با اجازه فورک میکنم یه مقدار روش کار کنم چندتا ایده دارم به نتیجه رسید پل میکنم

**Comment by HamedAp** [comment]
سلام .
Ssl , squid اتفاقا تو فکرم بود .
چند روزی هست درگیر یه مساله ای هستم و دستم بند هستش . انشالله دوباره ادامه میدم اپدیت هارو

**Comment by HamedAp** [comment]
بات تلگرام هم بفرستین حتما بررسی میکنم .

**Comment by OpiranClub** [comment]
> بات تلگرام هم بفرستین حتما بررسی میکنم .

[TG-Bot.txt](https://github.com/HamedAp/Ssh-User-management/files/10832898/TG-Bot.txt)

**Comment by HamedAp** [comment]
SSL اضافه شد و در صورت نیاز میتونین دستورش رو ران کنین تا پنل با SSL لود بشه

**Comment by HamedAp** [comment]
در مورد بات تلگرام هم میشه گفت دستم بازه و هر کاری که اون ربات داشت رو میتونم انجام بدم . فقط نگه داشتم همه امکانات رو اضافه کنم و بعد توی تلگرام اضافه کنم .

**Comment by OpiranClub** [comment]
are didam etefaghat code ro didam , man khodam ghablan gerefteh budam ba acme vali alie hala auto ssl hamrah ba cronjob ham dareh 

vali vaghean nemidunam chejury mahdudiate traffic mikhay bezary etefaghan kheily search kardam hich ja nadidam beshe user linux o ba traffic mahdud kard vali montazer mimunam faghat baraye in kar

**Comment by OpiranClub** [comment]
man ba ejazat baraye khodam englisish kardam (LOL)
faghat ye comment zahery dadash 

box user mangement ya hamun modiriate karbaran arrangementesh moshkel dareh yekam

**Comment by OpiranClub** [comment]
chat box ham man az crisp khodam tu footer gozashtam

**Comment by OpiranClub** [comment]
va ye comment dg beja restricted behtar nabud az login page estefadeh beshe?

**Comment by OpiranClub** [comment]
va folder "p" tu masire html ro ye ghesmat tu panel bezary baraye shakhsi sazi user haye maamuli man khodam changesh kardam vali dastresish tu panel tu box setting biad alie

**Comment by OpiranClub** [comment]
man telegram channel ham be menu ezafeh kardam ke inam mituni be nazaram shakhsi sazi beshe tu setting ke albate baste be khodet dareh be onvane sahebe asar

**Comment by OpiranClub** [comment]
vali asle kar ghesmate user panel mishe ina bishtar arayeshe kar budan ru oon daram kar mikonam ke user betuneh moshakhasate etesalesho bebineh dar vaghe ye static page ye moshakhasate etesalesho ba zadan user name va password betuneh bebineh

inam moghei mishe ke login page bashe ke beshe page admin o az user joda kard

**Comment by OpiranClub** [comment]
favicon ham baz mishe shakhsi sazi kard

**Comment by OpiranClub** [comment]
be nazaram joz footer ke emzaye khodete baghieye chiza ghabeliate shakhsi sazi beshan panele khassi mishe dar hadde xmplus

**Comment by OpiranClub** [comment]
ye morede dg ke dar ayandeh rush kar kon edgham chand server ruye yek panel

**Comment by OpiranClub** [comment]
bot telegram o ke gozashty va update kardy link github ro tu channel ha mizaram barat chon vaghean jaye hemayat dary dada

**Comment by HamedAp** [comment]
مرسی از همه توضیحات . 
همه کارهارو خیلی راحت میشه انجامش داد .
فقط چند روزه درگیر یه کار شخصی هستم و واقعا وقت نمیکنم رو پنل کار کنم . 
اگه مایل بودین Pull بزنین حتما استفاده می کنیم از نظراتتون .
