### ISSUE TITLE
غیرفعال کردن کاربر

### ISSUE THREAD

**Issue by rezazealott** [HamedAp/Ssh-User-management#23]
سلام و خسته نباشید 
در استاتوس کاربر رو غیرفعال نشون میده اما دستور اعمال نمیشه و کاربر میتونه همچنان وصل بشه .

**Comment by HamedAp** [comment]
سلام . به صورت دستی غیرفعال شده یا تاریخ انقضا غیرفعال کرده ؟

**Comment by rezazealott** [comment]
اگر به صورت دستی غیر فعال‌بشه، درست کار میکنه . اما اگر سیستماتیک بر اساس تاریخ انقضا کار کنه ، استاتوس رو غیر فعال میکنه ولی انگار usermod -L رو اعمال نمیکنه و فقط نمایی از اون رو توی اینترفیس نشون میده.

**Comment by HamedAp** [comment]
این مشکل هم حل شده و در آپدیت بعدی رفع خواهد شد . 
با تشکر از اطلاع رسانی
