### ISSUE TITLE
backup

### ISSUE THREAD

**Issue by zoobin65** [HamedAp/Ssh-User-management#24]
سلام
بخواهیم سرور و عوض کنیم چکار کنیم؟
یوزرها رو دوباره چطوری به پنل اضافه کنیم؟

**Comment by HamedAp** [comment]
سلام . قسمت بکاپ ، یک بکاپ بروز بسازید و فایلشو دانلود کنین .
در سرور جدید قسمت رستور میتونین فایل رو انتخاب کرده و اپلود کنید و سپس ریستور کنین

**Comment by zoobin65** [comment]
درسته
چون تو موبایل باز کردم منو ها نمایش داده نمی شد

اگه بشه تک کاربره کرد و حجم تعیین کرد عالی می شه

**Comment by HamedAp** [comment]
تک کاربره توی تنظیمات تب محدودیت هستش . ولی ترافیک فعلا دارم کار میکنم روش
