### ISSUE TITLE
عدم نمایش فیلترینگ و کاربران آنلاین

### ISSUE THREAD

**Issue by darklies** [HamedAp/Ssh-User-management#25]
من آخرین کد رو نصب کردم 
ولی هیچکدوم از فیلترینگ و کاربران آنلاینش کار نکرد

**Comment by HamedAp** [comment]
سیستم عامل اوبونتو هستین ؟

**Comment by reza2c** [comment]
منم دقیقا همین مشکل رو دارم ، اوبونتو 18.02

**Comment by HamedAp** [comment]
دلیل اش اینه که تو فایل ssh_config پورت رو آنکامند نکردین ! 
تو توضیحات Readme همه چی رو نوشتم .
پورت رو انکامند کنین و دوباره دستور نصب رو بزنین

**Comment by HamedAp** [comment]
دستور نصب رو دوباره بزنین این مشکل حل میشه .
تغییرات داده شد تا پورت رو آنکامند کنه  .

**Comment by reza2c** [comment]
بله مشکل از همون بود ، ممنون
