### ISSUE TITLE
NetHogs is not running

### ISSUE THREAD

**Issue by hamedheidari** [HamedAp/Ssh-User-management#258]
ترافیک مصرفی محاسبه نمیشه. NetHogs هم بصورت خودکار اجرا نمیشه. ولی نصب هس و دستی اجرا میشه. تعداد پورت فعال سرور زیاد نیس. فقط دو تا پورت (ک ۸۰ هم نیس) فروارد میشه با رت‌هول.

**Comment by HamedAp** [comment]
احتمالا به صورت دستی نصب کردین nethogs رو . 
کامل حذفش کنین و بعدش پنل رو اپدیت کنین

**Comment by hamedheidari** [comment]
بله، درسته. چون نمیتونه پنل نصبش کنه. بازم دوباره امتحان کردم و این پیام میاد نهایتاً:
/dev/fd/63: line 453: nethogs: command not found
Nethogs Is NOT Installed

**Comment by hamedheidari** [comment]
در نسخه ۲۰ ابونتو مشکل برطرف شد. کامند نصب NetHogs ک طی نصب پنل اجرا میشه، با نسخه ۲۴ سازگار نبود.
