### ISSUE TITLE
سرور مناسب برای ایرانسل و اینترنت ثابت

### ISSUE THREAD

**Issue by amin1562** [HamedAp/Ssh-User-management#26]
سلام و وقت بخیر؛
تشکر بابت کانفیگ شما بدون ایراد بالا میاد و مشکلی نداره؛متشکرم از زحماتتون

سوالی داشتم ازتون بنده روی سرور هلند و آلمان تست کردم،هلند با هر اینترنت ثابتی بالا میاد و مشکلی نداره ولی برای اینترنت ایرانسل به سختی کانکت میشه و چندین بار قطع میشه و میشه گفت وقتی هم که وصله کارایی نداره؛سرور آلمان هم ایرادی نداره به اینترنت ثابت ولی اینترنت همراه بسیار کند!

امکانش هست ارائه دهنده هاستی معرفی کنید که روی اینترنت ثابت و همراه بدون مشکل وصل شه.
ممنون

**Comment by HamedAp** [comment]
سلام وقت بخیر . مشکلات ایرانسل با ست کردن dns حل میشه .

**Comment by amin1562** [comment]
سلامی دوباره؛

من DNS گوگل و Cloudflare زدم ولی فرقی نکرد

![Screenshot (1387)](https://user-images.githubusercontent.com/81589398/222265078-c43fc3d8-2a48-455e-aafa-fc2e811e2e8c.png)

اطلاعات سرور هم

![Screenshot (1388)](https://user-images.githubusercontent.com/81589398/222265377-9b3ee0bd-8ac4-42f6-afe7-0036b33b3f65.png)
با ایپی 
92.63.168.150

امکانش هست چک کنید؛ روی اینترنت ثابت بدون ایراد بالا میاد ولی همراه ایراد داره
ممنون میشم راهنمایی کنید
اگه اطلاعات سرور هم خواستید امکانش باشه ایدی جایی معرفی کنید میفرستم براتون

**Comment by HamedAp** [comment]
منظورم سرور نبود ! 
منظورم رو اپلیکیشن ها بود ! 
تو تنظیمات نپستر بزنین کافیه

**Comment by amin1562** [comment]
![photo_5765021077301476286_y](https://user-images.githubusercontent.com/81589398/222282257-912832db-9cae-4756-bbda-417ed8d798dc.jpg)
![photo_5765021077301476290_x](https://user-images.githubusercontent.com/81589398/222282264-6658bd0d-9f58-4f1f-be81-8f20de2a7049.jpg)

دی ان اس گوگل تست کردم ولی همچنان عملکرد ضعیفی داره
پورت Udpgw هم دیفالت 7300 هست تغییر ندادم و تنها دی ان اس گوگل و کلود اضافه کردم

**Comment by HamedAp** [comment]
الان مشکل شما سرعت هستش یا وصل شدن ؟

**Comment by amin1562** [comment]
هردو

![photo_5764761777240914927_x](https://user-images.githubusercontent.com/81589398/222400401-1ead5345-2662-4961-8223-27e17a4dcf81.jpg)

**Comment by HamedAp** [comment]
میتونه از سرور باشه یا ایرانسل و همراه اول سرور های شما رو محدود کرده باشه .
تو صفحه فیلترینگ توی پنل ایران آنلاین هستش ؟

**Comment by amin1562** [comment]
![Screenshot (1390)](https://user-images.githubusercontent.com/81589398/222415346-09d655bb-ec2b-452e-8502-65ccf9e4b0f9.png)

**Comment by HamedAp** [comment]
> ![Screenshot (1390)](https://user-images.githubusercontent.com/81589398/222415346-09d655bb-ec2b-452e-8502-65ccf9e4b0f9.png)

دستور نصب رو دوباره بزنین . اپدیت میکنه و درست میشه اون مشکل

**Comment by HamedAp** [comment]
من از یه سایت خارجی میگیرم 

https://www.ethernetservers.com/clients/aff.php?aff=1571

با ارز دیجیتال میتونین بخرین

**Comment by merikh11** [comment]
سلام وقت بخیر
اول بگم دمتون حسابی گرم ایولا دارین با این کاری که انجام دادین امیددارم تنو دلتون همیشه سلامتو شاد باشه تا بیشترو بهترش کنید
مشکلی که من برخورد کردم بعد از نصب کد داخل هاب و گرفتن پنل دسترسیم به ارور دسترسی کاربر root ممنوع شد مواجع شدم نمیتونم وارد بشم 
راه حلی هستش ؟ یا اشتباهی انجام دادم ! که فک نکنم
