### ISSUE TITLE
محدودیت حجم کاربر

### ISSUE THREAD

**Issue by amirsemsari** [HamedAp/Ssh-User-management#29]
سلام.پنل خیلی خوبی هست.دستتون درد نکنه.

فقط دوتا سوال داشتم.محدودیت حجم کاربر کی فعال میشه؟؟؟

گزینه خروج از پنل رو نداره؟؟؟

**Comment by HamedAp** [comment]
سلام . محدودیت کاربر فعال هستش . 
در قسمت ویرایش کاربر میتونین تعداد بزنین چند نفر بتونه وصل شه . ( عدد صفر = بینهایت )
در قسمت تنظیمات هم میتونین گزینه رو فعال یا غیرفعال کنین .

**Comment by HamedAp** [comment]
خروج از پنل هم صفحه رو ببندنی خودکار خروج میزنه

**Comment by amirsemsari** [comment]
> سلام . محدودیت کاربر فعال هستش . در قسمت ویرایش کاربر میتونین تعداد بزنین چند نفر بتونه وصل شه . ( عدد صفر = بینهایت ) در قسمت تنظیمات هم میتونین گزینه رو فعال یا غیرفعال کنین .

محدودیت حجم دانلود رو منظورم بود.اون محدودیت یک‌کابره یا چندکاربره رو میدونم.ولی محدودیت حجم دانلود رو جایی ندیدم که بشه تنظیم کرد.

**Comment by HamedAp** [comment]
به زودی اونم اضافه میشه . یه مقدار سخت هست ولی شدنیه . 

چند روز زمان میبره

**Comment by bazres** [comment]
> به زودی اونم اضافه میشه . یه مقدار سخت هست ولی شدنیه .
> 
> چند روز زمان میبره

داداش من رمز پنل عوض کردم الان اصلا وارد نمیشه به پنل با هیچکدوم از رمزام چجوری ریستش کنم

**Comment by HamedAp** [comment]
> > به زودی اونم اضافه میشه . یه مقدار سخت هست ولی شدنیه .
> > چند روز زمان میبره
> 
> داداش من رمز پنل عوض کردم الان اصلا وارد نمیشه به پنل با هیچکدوم از رمزام چجوری ریستش کنم

با این دستور یوزر و پسورد ریست میشه :

mysql -e "use ShaHaN;drop table setting;"

**Comment by amirsemsari** [comment]
> به زودی اونم اضافه میشه . یه مقدار سخت هست ولی شدنیه .
> 
> چند روز زمان میبره

مهندس میگم یه گروه تلگرامی اگه میشه برای این پنل بزن.لینکشم بزار همینجا.توی گروه هم اطلاعیه ها و‌خبرها و باگ ها و آپدیت ها رو اعلام کن.

**Comment by HamedAp** [comment]
> > به زودی اونم اضافه میشه . یه مقدار سخت هست ولی شدنیه .
> > چند روز زمان میبره
> 
> مهندس میگم یه گروه تلگرامی اگه میشه برای این پنل بزن.لینکشم بزار همینجا.توی گروه هم اطلاعیه ها و‌خبرها و باگ ها و آپدیت ها رو اعلام کن.

داخل پنل هست لینک گروه
