### ISSUE TITLE
وضعیت

### ISSUE THREAD

**Issue by EbadiDev** [HamedAp/Ssh-User-management#3]
با سلام در این وضعیت اسفناک اینترنت، این روش SSH وضعیتش به چه شکل هست ؟ اگه مشکلی نداره ما هم کمک کنیم در این پروژه

**Comment by HamedAp** [comment]
سلام . 
سرعت بالا و مطمئن هستش .
امکان فیلتر شدنش کمتر از بقیه سرویس ها هستش . 
نصب کنین و تست کنین

**Comment by shirazishz** [comment]
درود حامد خان
امکان داره راهنمایی کنید پنل که زحمت کشیدی اسکرین شات گذاشتی چجوری نصب میشه؟

**Comment by HamedAp** [comment]
تو صفحه اصلی زدم .
یه دستور هستش . اونو میزنین .
ازتون ۲ تا مورد میپرسه .
یوزر ادمین
پشورد ادمین
هر چی دوست دارید بزنین .
بعد از نصب بهتون اطلاعات پنل و یزرو و پسورد رو میده

**Comment by shirazishz** [comment]
پنل با بروزر به آدرس آیپی(دامین رکورد شده در کلود فلر) باز میشه ؟

**Comment by HamedAp** [comment]
هر دو باز میشه . هم ای پی هم دامنه

**Comment by shirazishz** [comment]
من انجام دادم کاربر هم درست کردم فایل خروجی کجا میره؟
با چه برنامه کانکت شم

**Comment by HamedAp** [comment]
فایل خروجی نداره فعلا.
تو ایفون با برنامه napsternetv
تو اندروید هم همون برنامه هستش و http injector

**Comment by shirazishz** [comment]
خروجی کجا پیدا کنم (کانفیگ) ببرم داخل napsternetv

**Comment by HamedAp** [comment]
دستی باید ادد کنی
Server ip
Port
User
Password

**Comment by shirazishz** [comment]
ممنون

**Comment by Amiroirr** [comment]
سلام . خسته نباشید .
بنده اسکریپت رو ران کردم . ولی چون کاربران رو قبلا اضافه کرده بودم توی پنل صفر میزنه تعداد کاربران رو . راهی هست که بشه کاربران رو وارد پنل کرد ؟
ممنون از زحماتتون

**Comment by HamedAp** [comment]
> سلام . خسته نباشید . بنده اسکریپت رو ران کردم . ولی چون کاربران رو قبلا اضافه کرده بودم توی پنل صفر میزنه تعداد کاربران رو . راهی هست که بشه کاربران رو وارد پنل کرد ؟ ممنون از زحماتتون

سلام . 
باید دستی اضافه کنین فعلا . به زودی این مورد حل خواهد شد .

**Comment by Amiroirr** [comment]
یعنی با deluser پاک کنم بعد از طریق پنل بسازم . و یه مشکل دیگه اینکه از طریق پنل یوزر ساختم و با گوشی آنلاینم ولی توی پنل قسمت یوزر آنلاین صفر هست . پنل رو بستم دوباره وارد شدم بازم آنلاین یوزر رو نشون نداد

**Comment by irluca** [comment]
سلام من هرچقدر تست میکنم کانکت نمیشه؟
سرور از هتزنر میگیرم. امکان داره آی پی فیلتر شده باشه؟
ای پی به خوبی پینگ میده
به نظرتون مشکل از کجاست و چجوری میشه فهمید آی پی فیلتر شده.

**Comment by HamedAp** [comment]
> یعنی با deluser پاک کنم بعد از طریق پنل بسازم . و یه مشکل دیگه اینکه از طریق پنل یوزر ساختم و با گوشی آنلاینم ولی توی پنل قسمت یوزر آنلاین صفر هست . پنل رو بستم دوباره وارد شدم بازم آنلاین یوزر رو نشون نداد

نیازی به پاک کردن یوزر نیست .
همون یوزر رو دوباره ادد کنین با پسوردش .

انلاین هم احتمالا پورتش توی فایل کامند شده .
فایل /etc/ssh/sshd_config رو باز کنین و توش خط Port 22 رو آنکامند کنین .
بعد از این کار از طریق دستور دوباره نصب کنین .

**Comment by HamedAp** [comment]
> سلام من هرچقدر تست میکنم کانکت نمیشه؟ سرور از هتزنر میگیرم. امکان داره آی پی فیلتر شده باشه؟ ای پی به خوبی پینگ میده به نظرتون مشکل از کجاست و چجوری میشه فهمید آی پی فیلتر شده.

احتمالش هست قبل شما یه نفر همون ای پی رو گرفته و فیلتر شده باشه . پورت رو عوض کنین و دوباره نصب کنین تست کنین 
بالا توضیح دادم چجوری پورت رو تغییر بدین .

**Comment by irluca** [comment]
> 

پورت رو از داخل پنل عوض کنم مشکلی نداره؟ یا باید توی کانفیگ سرور عوض کرد؟

**Comment by HamedAp** [comment]
> > 
> 
> پورت رو از داخل پنل عوض کنم مشکلی نداره؟ یا باید توی کانفیگ سرور عوض کرد؟

احتمالا عوض نکنه .
شما اول فایل /etc/ssh/sshd_config رو باز کنین و توش پورت رو عوض کنین :
Port 1234
سیو کنین و خارج شین
systemctl restart sshd
بزنین
بعد دوباره پنل رو از طریق دستور نصب کنین .

**Comment by irluca** [comment]
> > > 
> > 
> > 
> > پورت رو از داخل پنل عوض کنم مشکلی نداره؟ یا باید توی کانفیگ سرور عوض کرد؟
> 
> احتمالا عوض نکنه . شما اول فایل /etc/ssh/sshd_config رو باز کنین و توش پورت رو عوض کنین : Port 1234 سیو کنین و خارج شین systemctl restart sshd بزنین بعد دوباره پنل رو از طریق دستور نصب کنین .

تست کردم توی پنل عوض کنی سرور رو عوض میکنه
ولی هر آی پی من تست میکنم بی فایده س
سرور وی پی اس از کجا پیشنهاد میکنید بگیرم؟

**Comment by HamedAp** [comment]
من خودم از این سایت میگیرم و لوکیشن امریکا داره فقط . سرور های یکساله ۱۵ دلاریش خوبه .

https://www.ethernetservers.com/clients/aff.php?aff=1571

**Comment by irluca** [comment]
> من خودم از این سایت میگیرم و لوکیشن امریکا داره فقط . سرور های یکساله ۱۵ دلاریش خوبه .
> 
> https://www.ethernetservers.com/clients/aff.php?aff=1571

unmanaged vps بگیرم؟

**Comment by HamedAp** [comment]
> > من خودم از این سایت میگیرم و لوکیشن امریکا داره فقط . سرور های یکساله ۱۵ دلاریش خوبه .
> > https://www.ethernetservers.com/clients/aff.php?aff=1571
> 
> unmanaged vps بگیرم؟

ثبت نام کنین . توی قسمت ثبت سرویس 
Unmanaged vps ( special offers ) 
سرور های یکساله هستش . هم قیمتش خوبه هم کیفیتش خوبه .

**Comment by irluca** [comment]
> > > من خودم از این سایت میگیرم و لوکیشن امریکا داره فقط . سرور های یکساله ۱۵ دلاریش خوبه .
> > > https://www.ethernetservers.com/clients/aff.php?aff=1571
> > 
> > 
> > unmanaged vps بگیرم؟
> 
> ثبت نام کنین . توی قسمت ثبت سرویس Unmanaged vps ( special offers ) سرور های یکساله هستش . هم قیمتش خوبه هم کیفیتش خوبه .

دو تا ipv4 میده؟
آی پیش اگه فیلتر بشه امکان عوض کردنش هست یا پولت رفته دیگه؟

**Comment by HamedAp** [comment]
> > > > من خودم از این سایت میگیرم و لوکیشن امریکا داره فقط . سرور های یکساله ۱۵ دلاریش خوبه .
> > > > https://www.ethernetservers.com/clients/aff.php?aff=1571
> > > 
> > > 
> > > unmanaged vps بگیرم؟
> > 
> > 
> > ثبت نام کنین . توی قسمت ثبت سرویس Unmanaged vps ( special offers ) سرور های یکساله هستش . هم قیمتش خوبه هم کیفیتش خوبه .
> 
> دو تا ipv4 میده؟ آی پیش اگه فیلتر بشه امکان عوض کردنش هست یا پولت رفته دیگه؟

ای پی فیلتر نمیشه . اگه بشه با یه دلار میتونین ای پی جدید بگیرین

**Comment by irluca** [comment]
> > > > > من خودم از این سایت میگیرم و لوکیشن امریکا داره فقط . سرور های یکساله ۱۵ دلاریش خوبه .
> > > > > https://www.ethernetservers.com/clients/aff.php?aff=1571
> > > > 
> > > > 
> > > > unmanaged vps بگیرم؟
> > > 
> > > 
> > > ثبت نام کنین . توی قسمت ثبت سرویس Unmanaged vps ( special offers ) سرور های یکساله هستش . هم قیمتش خوبه هم کیفیتش خوبه .
> > 
> > 
> > دو تا ipv4 میده؟ آی پیش اگه فیلتر بشه امکان عوض کردنش هست یا پولت رفته دیگه؟
> 
> ای پی فیلتر نمیشه . اگه بشه با یه دلار میتونین ای پی جدید بگیرین

کشور ایران رو داره واسه رجیستر کردن و شماره ایران رو قبول می کنه.
ولی چجوری پرداخت کنیم هزینه ش رو؟

**Comment by HamedAp** [comment]
> > > > > > من خودم از این سایت میگیرم و لوکیشن امریکا داره فقط . سرور های یکساله ۱۵ دلاریش خوبه .
> > > > > > https://www.ethernetservers.com/clients/aff.php?aff=1571
> > > > > 
> > > > > 
> > > > > unmanaged vps بگیرم؟
> > > > 
> > > > 
> > > > ثبت نام کنین . توی قسمت ثبت سرویس Unmanaged vps ( special offers ) سرور های یکساله هستش . هم قیمتش خوبه هم کیفیتش خوبه .
> > > 
> > > 
> > > دو تا ipv4 میده؟ آی پیش اگه فیلتر بشه امکان عوض کردنش هست یا پولت رفته دیگه؟
> > 
> > 
> > ای پی فیلتر نمیشه . اگه بشه با یه دلار میتونین ای پی جدید بگیرین
> 
> کشور ایران رو داره واسه رجیستر کردن و شماره ایران رو قبول می کنه. ولی چجوری پرداخت کنیم هزینه ش رو؟

ارز دیجیتال و پیپال
