### ISSUE TITLE
Kill user

### ISSUE THREAD

**Issue by amirsemsari** [HamedAp/Ssh-User-management#30]
سلام.برای یه کاربر خاص،گزینه kill user رو میزنم.اما ارتباطش قطع نمیشه.ولی وقتی kill all users رو میزنم،ارتباط همه یوزرها قطع میشه.

منظورم اینکه که فگ کنم گزینه kill user برای یک کاربر خاص،کار نمیکنه و باگ داره

**Comment by HamedAp** [comment]
سلام .
تا جایی که میدونم مشکلی نداره کیل .
چون چند بار تست کردم .
ولی حتما بررسی میکنم
