### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Amirmahdiphp** [HamedAp/Ssh-User-management#31]
سلام من پورتم رو بوردم 51401 و الان وصلم به فیلتر شکن اما کاربران آنلاین 0 هست
و یک سوال توی ویندوز با چه برنامه ای وصل بشم به SSH?
توی مک هم بگید؟

**Comment by HamedAp** [comment]
بعد از تغییر پورت دستور نصب رو بزنین تا پورت تو پنل عوض شه و انلاین ها درست شه !
ویندوز Netmod
مک رو نمیدونم
