### ISSUE TITLE
استفاده در ویندوز و لینوکس

### ISSUE THREAD

**Issue by mojtabashahosseinii** [HamedAp/Ssh-User-management#34]
با سلام خدمت شما
میخواستم بدونم روی ویندوز و لینوکس چطوری میشه به این vpn وصل شد
روی گوشی اندرویدی و ایفون با نرم افزار netsternetV وصل میشم
روی ویندوز و لینوکس رو زحمت بکشین راهنمایی بکنین ممنون میشم
ممنون

**Comment by HamedAp** [comment]
سلام .
روی ویندوز با برنامه Netmod میشه وصل شد .
لینوکس متاسفانه خبری ندارم

**Comment by mojtabashahosseinii** [comment]
من netmod رو نصب کردم و use ssh رو میزنم
پروفایلم اضافه میکنم
ولی روی reconnecting میمونه و ارورش هم اینکه ip lookup نمیتونه بکنه
روی دامنه هم تست کردم بازم کار نمیکنه
اگر امکانش هست بهم بگید چطوری هست ویندوز 11 کار میکنه یا نه ؟

ممنون
