### ISSUE TITLE
LoadBalancer

### ISSUE THREAD

**Issue by kazemim99** [HamedAp/Ssh-User-management#35]
یه مشکل بزرگی که این پروتکل داره درصورت افزایش کاربر شدیدا مصرف پردازنده میره بالا در این صورت باید سرور اضافه بشه یا منابع افزایش پیدا کنه پس بودن یک Loadbalancer از واجباته و امکان افزودن سرور

**Comment by HamedAp** [comment]
تعداد بالای ۶۰ نفر بشه سرور رو فیلتر میکنن ! 
بالای ۱۰۰ نفر اونی که شما میگین شاید باشه ! 
وگرنه ۱۴۰ نفر هم استفاده شده و مشکلی نداشته با رم ۱ گیگ

**Comment by kazemim99** [comment]
250 با تا همزمان رو سرور دارم  با این مشخصات

![image](https://user-images.githubusercontent.com/14816958/224300477-c07463b0-ecc2-4862-b691-9029baaf7374.png)
 cpu کم میاره
