### ISSUE TITLE
SSL Installer

### ISSUE THREAD

**Issue by kazemim99** [HamedAp/Ssh-User-management#36]
برای SSL Installer باید جای خاصی dns ست کنیم چون هرچی اسکریپت رو اجرا میکنه بدون مشکل میره ولی وارد سایت نمیشه 

![image](https://user-images.githubusercontent.com/14816958/224290296-02bf2046-5734-49d2-b85d-34159729d2b9.png)

![image](https://user-images.githubusercontent.com/14816958/224290485-4cc98e5b-0305-42d5-ae3d-73dcb39e1465.png)

**Comment by HamedAp** [comment]
بدون ssl هم سایتتون رو نمیاره ! 
چک کنین حتما روی ای پی سرور ست شده باشه !

**Comment by kazemim99** [comment]
اگه روی آی پی سرور ست نشده باشه ssl نصب نمیشه ارور میده در حالی که ssl با موفقیت نصب شد

**Comment by HamedAp** [comment]
> اگه روی آی پی سرور ست نشده باشه ssl نصب نمیشه ارور میده در حالی که ssl با موفقیت نصب شد

خوب عزیزم وقتی ست نشده انتظار داری چجوری ست بشه ؟ 😐
