### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by ramindoroozeh** [HamedAp/Ssh-User-management#37]
سلام بعد نصب ssl
اصلا باز نمیشه و این پیام میاد رو وب سرورش

Hi :) Bye :X

**Comment by HamedAp** [comment]
> سلام بعد نصب ssl اصلا باز نمیشه و این پیام میاد رو وب سرورش
> 
> Hi :) Bye :X

ادرس پنل : 
https://DOMAIN/p/
خواهد شد ! موقع نصب هم اطلاع داده میشه
