### ISSUE TITLE
کار نکردن کاربر همزمان

### ISSUE THREAD

**Issue by vanish666** [HamedAp/Ssh-User-management#38]
با سلام و تشکر بابت کمک شما به جامعه ایرانی
من مشکلی که با پنل دارم کار نکردن کاربر همزمان هستش. روی هر مقداری که ست میکنم، محدودیت اعمال نمیشه و تعداد کاربر بیشتر از عدد ست شده میتونن با اون اکانت متصل بشن.

**Comment by HamedAp** [comment]
از قسمت تنظیمات محدودیت کاربر رو فعال کنین
