### ISSUE TITLE
نصب نشدن ssl

### ISSUE THREAD

**Issue by ramindoroozeh** [HamedAp/Ssh-User-management#39]
سلام من بادستور ssl نصب میکنم و ساب دامین میدم ولی اصلا باز نمیشه

**Comment by HamedAp** [comment]
چی باز نمیشه ؟

**Comment by ramindoroozeh** [comment]
url که میده

**Comment by HamedAp** [comment]
> url که میده

ادرس پنل به این ترتیب خواهد بود  :
https://IP-SERVER/p/index.php
این لینک رو باز نمی کنه ؟
