### ISSUE TITLE
کار نکرد

### ISSUE THREAD

**Issue by kingabsent** [HamedAp/Ssh-User-management#4]
با سلام 
کار نمیکنه

نصب کردم اومد بالا
ولی کار نکرد
فکر کنم باید روی سرور ایران بزنم بعد تانل کنم روی خارج

**Comment by HamedAp** [comment]
> با سلام کار نمیکنه
> 
> نصب کردم اومد بالا ولی کار نکرد فکر کنم باید روی سرور ایران بزنم بعد تانل کنم روی خارج

نه نیازی به تانل نداره . 
پورت ۲۲ استفاده میکنین ؟
احتمالا از پورت باشه .

**Comment by kingabsent** [comment]
پورت 2020
و 9794 امتحان کردم
پورت پیشنهادیتون چیه؟

**Comment by HamedAp** [comment]
سرور هتزنر دارید ؟
چند نفر با هتزنر مشکل داشتند ! 
من خودم ۵۸۲۹ استفاده میکنم و مشکلی نداره

**Comment by kingabsent** [comment]
کاش میشد چند تا سرور رو به یک پنل وصل کنیم

**Comment by kingabsent** [comment]
توی توضیحات زده بودید قابلیت اتصال به روبات تلگرام

**Comment by kingabsent** [comment]
چند تا اراد داشت
عدم ویرایش کاربر ساخته شده 
در صورت امکان تعداد کاربر ها رو بشه مدریت کرد مثلا تک کاربره یا بیشتر
اگر بشه چند تا سرور رو بشه به یک پنل اتصال داد که خیلی عالی میشه

**Comment by HamedAp** [comment]
> کاش میشد چند تا سرور رو به یک پنل وصل کنیم

در حال ساخت دیتابیس هستیم و میتونین اون کار رو بکنین . یکی دو هفته ای اپدیت جدید با امکانات جدید میاد حتما

**Comment by HamedAp** [comment]
> توی توضیحات زده بودید قابلیت اتصال به روبات تلگرام

قابلیت نبود . نوشتم اضافه خواهد شد . در برنامه هست که اضافه بشه حتما

**Comment by kingabsent** [comment]
در کل عالی بود 
واقعا دمتون گرم

**Comment by kingabsent** [comment]
نمیشه برای این سرویس کانکشن اختصاصی بنویسید؟
البته با هزینه

**Comment by HamedAp** [comment]
> نمیشه برای این سرویس کانکشن اختصاصی بنویسید؟ البته با هزینه

منظورتون از اختصاصی چیه ؟

**Comment by kingabsent** [comment]
یه چیزی مثل nv   ولی با پنل مدیریت که بشه از طریق پنل اطلاعات سرور رو وارد کرد

**Comment by HamedAp** [comment]
> یه چیزی مثل nv ولی با پنل مدیریت که بشه از طریق پنل اطلاعات سرور رو وارد کرد

منظورتون فایل کانفیگ هستش ؟

**Comment by kingabsent** [comment]
فایل کانفیگ هم باشه خوبه
ولی منظورم اینه که کانکشن یه پنل تحت وب داشته باشه که ادمین فایل کانفیگ بزاره برای کاربرها
و دیگه لازم نباشه تک تک کاربرا کانفیگ کنند یا فایل کانفیگ بزارن

**Comment by HamedAp** [comment]
> فایل کانفیگ هم باشه خوبه ولی منظورم اینه که کانکشن یه پنل تحت وب داشته باشه که ادمین فایل کانفیگ بزاره برای کاربرها و دیگه لازم نباشه تک تک کاربرا کانفیگ کنند یا فایل کانفیگ بزارن

میشه پنل جدا برای یوزر ها ساخت . که بتونن وارد شن و ترافیک شون رو ببینند یا تمدید کنند .

**Comment by kingabsent** [comment]
متوجه منظورم نشدید انگار
فرض کنید یه نرم افزار مثلnv  دارید 
که به بک پنل تحت وب وصل هست و شا چندین سرور رو کانفیگ میکنید و کانفیگ رو از طریق پنل مدیریت به نرم افزار اندروید انتقال میدید و کاربرها بدون وارد کردن کانفیگ (چون شما وارد کردید از طریق کنترل پنل )میتونن به سرور ها وصل بشن

**Comment by HamedAp** [comment]
> متوجه منظورم نشدید انگار فرض کنید یه نرم افزار مثلnv دارید که به بک پنل تحت وب وصل هست و شا چندین سرور رو کانفیگ میکنید و کانفیگ رو از طریق پنل مدیریت به نرم افزار اندروید انتقال میدید و کاربرها بدون وارد کردن کانفیگ (چون شما وارد کردید از طریق کنترل پنل )میتونن به سرور ها وصل بشن

این کار امکانش هست با سیستم اکانتینگ . ولی جزو اخرین اپدیت ها باید باشه چون پنل باید کاملا بدون باگ باشه بعد سیستم اکانتینگ ران بشه .
