### ISSUE TITLE
نشان ندادن کاربر های ساخته شده

### ISSUE THREAD

**Issue by SoroushImanian** [HamedAp/Ssh-User-management#40]
سلام وقت بخیر

من یوزر میسازم ولی بعدش تو قسمت یوزر ها لیست به صورت خالی هست  و نمیشه یوزر ها رو دید و مدیریت کرد 

مشکل از کجاست؟
![s](https://user-images.githubusercontent.com/109761123/224692717-6d7fa9b6-36b3-46a0-a4c1-0682d6b95356.png)

**Comment by HamedAp** [comment]
سلام . دستور نصب رو دوباره بزنین . احتمالا کامل نصب نشده .
اوبونتو یا سنتوس هستین ؟

**Comment by SoroushImanian** [comment]
ابونتو  (Ubuntu 20.04.5 LTS)

دوباره نصب کردم و دوباره مثل قبل هستش

رفتم passwd رو چک کردم یوزر رو ساخته ولی اصلا فقط یوزر های قبلی رو نشون میده جدید های که تو پنل میسازم رو نشون نمیده

**Comment by HamedAp** [comment]
تلگرام تو گروه پیام بدین مشکل حل کنیم .
https://t.me/ShaHaNPanel
