### ISSUE TITLE
هیچی

### ISSUE THREAD

**Issue by mmdjvdad** [HamedAp/Ssh-User-management#43]
چطوری باید ورود کرد. من هر کاری میکنم نمیشه. نه با دامنه نه با همون لینکی که خودش میده

**Comment by HamedAp** [comment]
چه خطایی میده ؟ عکس بفرستین

**Comment by FarzadMohtasham** [comment]
بنده نصب کردم یه صفحه سفید بالا میاد و چیزی نشون نمیده، کدهای HTML رو که چک کردم دیدم تگ Body کاملا خالیه و چیزی توش نوشته نشده

**Comment by staramid** [comment]
خطای پروکسی و فایروال میده.

**Comment by HamedAp** [comment]
عکس بفرستین ! 
همچین خطایی نداریم اخه

**Comment by mmdjvdad** [comment]
خطا نمیده. صفحه سفید هست اسم سایت رو هم میزنه شاهان فکر کنم

**Comment by HamedAp** [comment]
> خطا نمیده. صفحه سفید هست اسم سایت رو هم میزنه شاهان فکر کنم

دستور نصب رو دوباره بزنین . احتمالا کامل نصب نشده !

**Comment by staramid** [comment]
حامد جان من صفحم بالا اومد 
اما وقتی ufw فعال باشه صفحه بالا نمیاد. حتی پورت ها رو وارد ufw کردم اما وفتی  ufw فعال باشه اجازه دسترسی رو به پیج نمیده.
پیشنهاد شما چیه؟

**Comment by HamedAp** [comment]
پورت ۸۰ و ۴۴۳ رو باز کنین .

یا ufw غیرفعال کنین
