### ISSUE TITLE
پیشنهاد یه ویژگی بسیار مفید

### ISSUE THREAD

**Issue by FarzadMohtasham** [HamedAp/Ssh-User-management#46]
سلام آقای حامد عزیز، ممنون از ابزاری که طراحی و در اختیار عموم قرار دادین
میخواستم پیشنهادی بدم که میتونه بسیار مفید باشه، اگه بتونین قابلیتی به ابزار SSH-User-Management اضافه کنین که بشه باهاش از خروج ترافیک به سایت‌ها و اپلیکیشن‌های ایرانی جلوگیری کرد خیلی خوب میشه

مثل ابزاری که برای V2Ray درست کرده بودن که باهاش میشد سایت‌های ایرانی رو از سمت سرور بلاک کرد

باتشکر

**Comment by Hamid-Najafi** [comment]
با توجه به ارسال تمام داده‌ها از سمت کاربر به سرور، این فیچر به سادگی قابل انجام نیست مگر اینکه یک سرور دوم دیگه هم تهیه بشه و در سرور خارجی، بسته های با ایپی خاص مسیریابی بشوند به سرور دومی...منطقی نیست...

**Comment by FarzadMohtasham** [comment]
پس یعنی حتی با فایروال هم قابل انجام نیست؟ من با UFW و iptables و... تست کردم کار نکردن و نتونستن از خروج داده به سرور سایت‌های ایرانی جلوگیری کنن، اگه کسی راه حلی برای اینکار توی SSH Tunnel سراغ داره ارائه بده همینجا، ممنون

**Comment by HamedAp** [comment]
سلام . میشه روت نوشت واسه این کار ! 
یه مدت صبر کنین میشه روش کار کرد .

**Comment by mmdjvdad** [comment]
جالبه اگه زحمتشو بکشید دستتون درد نکنه ویژگی خوبیه.

**Comment by FarzadMohtasham** [comment]
ممنون برادر
