### ISSUE TITLE
آدرس صفحه مدیریت  

### ISSUE THREAD

**Issue by staramid** [HamedAp/Ssh-User-management#48]
ip/port/index php
or 
ip/p/index.php
?

**Comment by staramid** [comment]
حامد جان این صفحه بعد از نصب دفعه اول میلد بالا ، له محض بستن صفحه ، دیگه بالا نمیاد
ارور فایروال و پروکسی میده!

**Comment by HamedAp** [comment]
بعد از نصب نشون میده خوب ! 
Ip/p/
