### ISSUE TITLE
پیشنهاد و اشکالات

### ISSUE THREAD

**Issue by HamedAp** [HamedAp/Ssh-User-management#5]
چند تا اراد داشت
عدم ویرایش کاربر ساخته شده 
در صورت امکان تعداد کاربر ها رو بشه مدریت کرد مثلا تک کاربره یا بیشتر
اگر بشه چند تا سرور رو بشه به یک پنل اتصال داد که خیلی عالی میشه

_Originally posted by @kingabsent in https://github.com/HamedAp/Ssh-User-management/issues/4#issuecomment-1416841519_

**Comment by Amiroirr** [comment]
سلام مهندس . من با اس اس اچ تونل با ایرانسل مشکل دارم . کلا کانکت نمیشم . چند بار پورت هم عوض کردم ولی فقط با همراه اول وصل شد . ممنون میشم بگین چیکار باید بکنم

**Comment by HamedAp** [comment]
> سلام مهندس . من با اس اس اچ تونل با ایرانسل مشکل دارم . کلا کانکت نمیشم . چند بار پورت هم عوض کردم ولی فقط با همراه اول وصل شد . ممنون میشم بگین چیکار باید بکنم

اگه شیائومی هستین باید تو تنظیمات گوشی DNS رو روی خودکار بزارید و گوشی رو ریستارت کنین .
اگه اندروید هستین از برنامه http injector استفاده کنین و توی تنظیمات برنامه Set DNS رو روی کاستوم بزارید و 1.1.1.1 و 1.0.0.1 رو ست کنین .

**Comment by kademus** [comment]
من نصب کردم اما خطای زیر نمایش داده میشه و پنل وب بالا نمیاد 

sed: -e expression #1, char 11: unterminated `s' command

**Comment by HamedAp** [comment]
> من نصب کردم اما خطای زیر نمایش داده میشه و پنل وب بالا نمیاد
> 
> sed: -e expression #1, char 11: unterminated `s' command

اوبونتو هستین ؟ 🤔
apt upgrade -y 
بزنین اول همه چی اپگرید شه بعد

**Comment by Amiroirr** [comment]
> > سلام مهندس . من با اس اس اچ تونل با ایرانسل مشکل دارم . کلا کانکت نمیشم . چند بار پورت هم عوض کردم ولی فقط با همراه اول وصل شد . ممنون میشم بگین چیکار باید بکنم
> 
> اگه شیائومی هستین باید تو تنظیمات گوشی DNS رو روی خودکار بزارید و گوشی رو ریستارت کنین . اگه اندروید هستین از برنامه http injector استفاده کنین و توی تنظیمات برنامه Set DNS رو روی کاستوم بزارید و 1.1.1.1 و 1.0.0.1 رو ست کنین .

با http injector انجام دادم ولی نشد

**Comment by HamedAp** [comment]
> > > سلام مهندس . من با اس اس اچ تونل با ایرانسل مشکل دارم . کلا کانکت نمیشم . چند بار پورت هم عوض کردم ولی فقط با همراه اول وصل شد . ممنون میشم بگین چیکار باید بکنم
> > 
> > 
> > اگه شیائومی هستین باید تو تنظیمات گوشی DNS رو روی خودکار بزارید و گوشی رو ریستارت کنین . اگه اندروید هستین از برنامه http injector استفاده کنین و توی تنظیمات برنامه Set DNS رو روی کاستوم بزارید و 1.1.1.1 و 1.0.0.1 رو ست کنین .
> 
> با http injector انجام دادم ولی نشد

تنظیمات هم ست کردین ؟

**Comment by Amiroirr** [comment]
> > > سلام مهندس . من با اس اس اچ تونل با ایرانسل مشکل دارم . کلا کانکت نمیشم . چند بار پورت هم عوض کردم ولی فقط با همراه اول وصل شد . ممنون میشم بگین چیکار باید بکنم
> > 
> > 
> > اگه شیائومی هستین باید تو تنظیمات گوشی DNS رو روی خودکار بزارید و گوشی رو ریستارت کنین . اگه اندروید هستین از برنامه http injector استفاده کنین و توی تنظیمات برنامه Set DNS رو روی کاستوم بزارید و 1.1.1.1 و 1.0.0.1 رو ست کنین .
> 
> با http injector انجام دادم ولی نشد

ایرانصل روی پرت خاصی کانکت میشه ؟‌چون من پورت های زیادی تست کردم ولی نشد

**Comment by kademus** [comment]
> > من نصب کردم اما خطای زیر نمایش داده میشه و پنل وب بالا نمیاد
> > sed: -e expression #1, char 11: unterminated `s' command
> 
> اوبونتو هستین ؟ 🤔 apt upgrade -y بزنین اول همه چی اپگرید شه بعد

بله، سرور آپدیت و آپگریده اما این خطا رو میده.
بعد نصب اطلاعاتم بادوتا پورت بهم نشون داد. یکی پورتی که خودم ست کردم یکی پورتی که دیفالته، اگه اینو موقع نصب بپرسه خیلی خوب میشه.

**Comment by Amiroirr** [comment]
> > > > سلام مهندس . من با اس اس اچ تونل با ایرانسل مشکل دارم . کلا کانکت نمیشم . چند بار پورت هم عوض کردم ولی فقط با همراه اول وصل شد . ممنون میشم بگین چیکار باید بکنم
> > > 
> > > 
> > > اگه شیائومی هستین باید تو تنظیمات گوشی DNS رو روی خودکار بزارید و گوشی رو ریستارت کنین . اگه اندروید هستین از برنامه http injector استفاده کنین و توی تنظیمات برنامه Set DNS رو روی کاستوم بزارید و 1.1.1.1 و 1.0.0.1 رو ست کنین .
> > 
> > 
> > با http injector انجام دادم ولی نشد
> 
> تنظیمات هم ست کردین ؟

بله

**Comment by bazres** [comment]
محدودیت تک کاربره کردن اکانت جواب نمیده
کاربر انلاینم نمایش نمیده
مشکل از کجاس

**Comment by HamedAp** [comment]
> محدودیت تک کاربره کردن اکانت جواب نمیده کاربر انلاینم نمایش نمیده مشکل از کجاس

احتمالا پورت شما رو شناسایی نکرده .
به صورت دستی بزنین تو فایل های : 
/var/www/html/p/menu.php
/var/www/html/p/kill.php
خط دوم

**Comment by bazres** [comment]
> > محدودیت تک کاربره کردن اکانت جواب نمیده کاربر انلاینم نمایش نمیده مشکل از کجاس
> 
> احتمالا پورت شما رو شناسایی نکرده . به صورت دستی بزنین تو فایل های : /var/www/html/p/menu.php /var/www/html/p/kill.php خط دوم

چطور چنتا پورت اضافه کنم بهش؟

**Comment by bazres** [comment]
> > > > محدودیت تک کاربره کردن اکانت جواب نمیده کاربر انلاینم نمایش نمیده مشکل از کجاس
> > > 
> > > 
> > > احتمالا پورت شما رو شناسایی نکرده . به صورت دستی بزنین تو فایل های : /var/www/html/p/menu.php /var/www/html/p/kill.php خط دوم
> > 
> > 
> > چطور چنتا پورت اضافه کنم بهش؟
> 
> فعلا نمیشه . اپدیت های بعدی میشه واسه هر یوزر پورت خاصی تعریف کرد

اگ بشه محدودیت حجمی هم بهش اضافه بشه با درنظر گرفتن سرور واسط ایران عالی میشه

**Comment by reza2c** [comment]
سلام مهندس ، وارد سایت نمیشه و ارور تایم اوت میده
