### ISSUE TITLE
معرفی یک نرم افزار برای SSH Tunneling

### ISSUE THREAD

**Issue by FarzadMohtasham** [HamedAp/Ssh-User-management#50]
سلام دوست عزیز

توی ویندوز برای استفاده از SSH Tuneling & Port Forwarding بایستی اول دستور زیر رو وارد کنیم:
 ssh -p 56555 -N -D 5060 root@server.com
بعدش توی Nekoray یک کانکشن Socks درست کنیم که به پورت 5060 توی سیستم اشاره میکنه و حالت VPN Mode رو هم فعال کنیم تا تمامی داده‌های اینترنت از این پورت رد و بدل بشن، میخواستم ببینم نرم افزاری نیست که این پیچیدگی رو کم کنه تا نیاز نباشه هربار توی CMD اون دستور رو وارد کنیم و بعدش Nekoray رو بالا بیاریم؟

اگر شما نرم افزار خوبی رو سراغ دارین ممنون میشم معرفی کنین

**Comment by HamedAp** [comment]
Netmod

**Comment by FarzadMohtasham** [comment]
مشکلی که داره روی کل سیستم به صورت VPN Mode فعال نمیکنه و فقط پروکسی میکنه

**Comment by HamedAp** [comment]
فعلا بهترین برنامه هستش !
