### ISSUE TITLE
نحوه باز کردن لینک تو مرورگر

### ISSUE THREAD

**Issue by mmdrzrnjdst** [HamedAp/Ssh-User-management#52]
وقت بخیر
چجوری میتونم این لینک رو تو مرورگر باز کنم؟
http://xx.XXX.XXX.xxx/p/index.php
وقتی باز میکنم شروع میکنه یه فایل php رو دانلود کردن
ممنون میشم راهنمایی کنید 
با تشکر

**Comment by HamedAp** [comment]
سلام . مرورگرتون رو عوض کنین یا تنظیماتشو ریست کنین .
مشکل از مرورگر هستش که به جای نمایش فایل های php داره دانلودش میکنه .

**Comment by mmdrzrnjdst** [comment]
با chrome و edge امتحان کردم ولی هر دوتاش دانلود میکنن

**Comment by HamedAp** [comment]
یه فایل txt درست کنین .
پسوندشو تغییر بدین به php
بعد کلیک راست کنین open with 
کروم انتخاب کنین .

اگه نشد یه سرچ بزنین درست میشه .

**Comment by mmdrzrnjdst** [comment]
هرکاری میکنم نمیشه 
یه سوال نکنه پورت ssh رو عوض کردم از اونه؟

**Comment by HamedAp** [comment]
نه ربطی به پورت نداره !
مشکل از مرورگر هستش و یا کامپیوتر شما ! 
با گوشی باز کنین ببینین میشه ؟

**Comment by mmdrzrnjdst** [comment]
نه کد php رو باز کرد

**Comment by HamedAp** [comment]
بیاین گروه تلگرام :
https://t.me/ShaHaNPanel
