### ISSUE TITLE
مشکل SSH Port forwarding با تماس‌های تلگرام و واتس‌اپ

### ISSUE THREAD

**Issue by FarzadMohtasham** [HamedAp/Ssh-User-management#56]
سلام دوست عزیز
تا اونجایی که اطلاع دارم SSH Port Forwarding روی پروتکل TCP هستش و از این پروتکل برای انتقال داده استفاده میکنه و انگار این پروتکل با تماس‌های صوتی واتس‌اپ و تلگرام مشکل داره و برای حل مشکل بایستی از پروتکل UDP استفاده کرد(نمیدونم درسته یا نه)، ممنون میشم راهنمایی کنید تا مشکل تماس صوتی تلگرام و واتس‌اپ با SSH حل بشه، ممنون

**Comment by HamedAp** [comment]
سلام . تو کد ها هستش یه کد با نام ssh-calls که اجرا کنین واستون فعال میکنه .

**Comment by FarzadMohtasham** [comment]
فایل ssh-calls.sh رو دانلود کردم رو سرور از طریق wget و بعدش رانش کردم و این خطا رو میده:
./ssh-calls.sh: line 8: syntax error near unexpected token `newline'
./ssh-calls.sh: line 8: `<!DOCTYPE html>'

**Comment by FarzadMohtasham** [comment]
دستورات رو هم دونه به دونه به صورتی دستی اجرا کردم ولی این خطا رو داد:

`
root@vps20092:~# systemctl status rc-local.service
× rc-local.service - /etc/rc.local Compatibility
     Loaded: loaded (/lib/systemd/system/rc-local.service; static)
    Drop-In: /usr/lib/systemd/system/rc-local.service.d
             └─debian.conf
     Active: failed (Result: exit-code) since Thu
2023-03-23 19:09:27 UTC; 1min 2s ago
       Docs: man:systemd-rc-local-generator(8)
    Process: 1257539 ExecStart=/etc/rc.local start (c
ode=exited, status=127)
        CPU: 5ms
Mar 23 19:09:27 vps20092.org systemd[1]: Starting /etc/rc.local Compatibility...
Mar 23 19:09:27 vps20092.org rc.local[1257539]: /etc/rc.local: 3: 127.0.0.1:7300: not found
Mar 23 19:09:27 vps20092.org systemd[1]: rc-local.service: Control process ex
ited, code=exited, status=127/n/a
Mar 23 19:09:27 vps20092.org systemd[1]: rc-local.service: Failed
 with result 'exit-code'.
Mar 23 19:09:27 vps20092.org systemd[1]: Failed to start /etc/rc.local Compat
ibility.
`

**Comment by FarzadMohtasham** [comment]
به صورت دستی کدها رو اجرا کردم اوکی شد، ممنون

**Comment by FarzadMohtasham** [comment]
سلام مجدد، ممنون از تمامی زحماتی که میکشید دوست عزیز
همونطور که میدونین مشکل تماس توی تلگرام و واتس‌اپ رو داشتم با SSH Port Forwarding که توصیه کردین اسکریپت‌های موجود در فایل ssh-calls.sh رو اجرا کنم تا مشکل درست بشه
مشکل حل شد ولی بعضی وقت‌ها سرویس badvpn-udpgw شدیدا cpu مصرف میکنه و ۱۰۰ درصد میشه مصرف cpu سرور

به نظرتون این مشکل از چیه؟

![Screenshot (439)](https://user-images.githubusercontent.com/48632860/227746076-baffe474-fcb6-46de-adad-3fe548a04dd3.png)

**Comment by HamedAp** [comment]
این مورد باید بهینه بشه . انشالله به زودی بهینه میکنیم و اپدیت میکنیم اسکریپت رو

**Comment by FarzadMohtasham** [comment]
ممنون، چک کردم انگار وقتی زنگ میزنم به یکی این حجم از مصرف cpu به وجود میاد و بعدش درست میشه، پس منتظر میمونم تا آپدیت کنین، تشکر
