### ISSUE TITLE
بارگذاری فایل آموزشی در کانال تلگرام

### ISSUE THREAD

**Issue by amir9213** [HamedAp/Ssh-User-management#57]
سلام دوست عزیز، اول از همه ممنون بابت زحماتی که کشیدی

راستش من تونستم از لینک شما استفاده کنم و پنل رو روی سرور نصب کنم اما تو این کارا خیلی مبتدیم و تازه شروع کردم اگر امکانش باشه بصورت ساده آموزش نصب رو بصورت ترجیحا ویدیئو داخل کانال تلگرام آپلود کنید و اگر هم یک ویدئو هم برای رفع خطاهای احتمالی (تو هنگام تنظیم کردن دامنه به مشکل خوردم و هنوز هم نتونستم رفعش کنم) خیلی خوب میشه

ممنون از شما

**Comment by HamedAp** [comment]
با سلام
به زودی اموزش کامل توی پنل قرار میگیره .
