### ISSUE TITLE
باز نشدن پنل از طریق دامنه

### ISSUE THREAD

**Issue by amir9213** [HamedAp/Ssh-User-management#59]
سلام دوست عزیز
من دامنه رو ثبت کردم و همه چیز به صورت کامل انجام شد 
به دامنه م name server های cloudflare رو دادم و الان وقتی میخوام با استفاده از دامنه وارد پنل بشم وارد نمیشه 
اون A record هم که ثبت کردم به عنوان زیر دامنه هم با حالت proxy mode امتحان کردم هم با حالت dns only ولی با دو حالت نتونستم وارد پنل شم 
(نصب کردن ssl داخل ترمینال بدون مشکل انجام شده)
ممنون از شما

**Comment by amir9213** [comment]
> سلام . دامنه رو پینگ کنین ببینین ای پی سرور رو میاره یا نه !

پینگ کردم و آی پی رو بهم نشون داد

**Comment by HamedAp** [comment]
نباید مشکلی داشته باشه . چه خطایی میده بهتون ؟

**Comment by amir9213** [comment]
> > سلام . دامنه رو پینگ کنین ببینین ای پی سرور رو میاره یا نه !
> 
> پینگ کردم و آی پی رو بهم نشون د

> نباید مشکلی داشته باشه . چه خطایی میده بهتون ؟

هیچ خطایی رو به من نشون نمیده و داخل ترمینال همه چیز درست نصب شده 
توی مرورگرهای متفاوت هم امتحان کردم و من وقتی با آدرس دامنه میخوام وارد شم باز هم هیچ اروری نمیده 
صفحه یه ریلود میشه و میره روی https://www.google.com (از مرورگر فایرفاکس امتحان میکنم و مرورگرهای دیگر رو هم امتحان کردم)

دامنه م xyz هستش مشکلی نداره؟

**Comment by amir9213** [comment]
سلام دوست عزیز،
با گذشت تقریبا 2 ساعت این مشکل مرتفع شد 
احتمالا مشکل از سمت cloudflare بوده و الان همه قسمت ها به خوبی کار میکنن.
ممنون از تمام زحمات شما
