### ISSUE TITLE
همکاری

### ISSUE THREAD

**Issue by hiddify1** [HamedAp/Ssh-User-management#62]
سلام داداش
خیلی خوشم اومد از پنلتون
ما خیلی وقته هدف داریم برای مردم یه پنل ساده بیاریم بالا
اگه دوست داشتید همکاری کنیم

**Comment by HamedAp** [comment]
سلام . ممنون از لطفتون .  
راستش پنل شما رو من ندیدم و امکاناتشو نمیدونم .
اگر کاری از دستم بر میاد در خدمتم
