### ISSUE TITLE
گزارش مشکل

### ISSUE THREAD

**Issue by FarzadMohtasham** [HamedAp/Ssh-User-management#63]
سلام دوست عزیز
ممنون از تمامی زخماتی که برای پنل خوبتون میکشین
یه مشکلی رو پیدا کردم که وقتی یه روز میسازم و میرم تنظیماتش و تعداد کاربر همزمان رو تغییر میدم و سیو میکنم مشکلی نداره
ولی وقتی میخوام قسمت موبایل رو تغییر بدم و سیو میزنم میره صفحه سفید 
ممنون میشم چک کنین

**Comment by mmdjvdad** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/122828400/228044861-b59464ea-d79b-455f-a499-eb318697f29c.png)
سلام با نصب پنل دسترسی اس اس اچ به سرور مسدود میشه.

**Comment by HamedAp** [comment]
پورت رو عوض کردین ؟

**Comment by mmdjvdad** [comment]
به محض استارت سرور پورت رو ۴۴۳ میکنم. بعد شروع به نصب میکنم. با اولین ریبوت بعد از نصب پنل، دیگه دسترسی بسته میشه و مجبور میشم ریبیلد کنم، یوزر ها هم متصل نمیشن، گویا کلا اس اس اچ رو از کار میندازه. بعد رفتم پورت رو عوض کردم و پورت جدید رو در پنل وارد کردم و سیو زدم، دیگه نه پنل باز شد نه دسترسی داشتم.

**Comment by HamedAp** [comment]
وقتی پورت ۴۴۳ انتخاب میکنین دیگه نباید ssl رو بزنین !

**Comment by mmdjvdad** [comment]
حله اقا دمتون گرم فردا باز تست میکنم ❤️❤️
