### ISSUE TITLE
مشکل اپدیت جدید

### ISSUE THREAD

**Issue by FarzadMohtasham** [HamedAp/Ssh-User-management#64]
سلام، پنل رو یکبار آپدیت زدم ولی به روز رسانی نشد، بعدش دوباره کد آپدیت رو زدم دیگه پنل بالا نمیاد و This page isn’t working میده
ممنون میشم بررسی کنین برادر

و همچنین خیلی ممنون بابت اضافه کردن قابلیت محدودیت حجم

**Comment by mmdjvdad** [comment]
سلام بعد از وارد کردن یوزرنیم و پسورد دیگه هیچی نمیاد. و page not working میده

**Comment by FarzadMohtasham** [comment]
> سلام بعد از وارد کردن یوزرنیم و پسورد دیگه هیچی نمیاد. و page not working میده

آره دقیقا

**Comment by HamedAp** [comment]
سلام . 
مشکل php ورژن 8 بود که اپدیت جدید حل کرد موضوع رو 
دستور نصب رو دوباره بزنین حل میشه

**Comment by FarzadMohtasham** [comment]
ممنون برادر❤️
