### ISSUE TITLE
باگ ترافیک مصرفی

### ISSUE THREAD

**Issue by amirnet73** [HamedAp/Ssh-User-management#70]
سلام.وقتی کاربری رو کلا رو حذف میکنیم،در قسمت  ترافیک مصرف شده کاربران، همچنان نام کاربری اش و مقدار ترافیکی که مصرف کرده،وجود داره.

2-اخیرا هرچقد کاربران ترافیک مصرف میکنند در قسمت ترافیک مصرفی کاربران،هیچی تغییری برای آن کاربران صورت نمیگیرد

**Comment by HamedAp** [comment]
مورد اول که گفتین اپدیت بعدی درست میشه . 
مورد دوم هم سرور رو ریبوت کنین درست میشه
