### ISSUE TITLE
مشکل محدودیت کاربر

### ISSUE THREAD

**Issue by mory** [HamedAp/Ssh-User-management#71]
سلام، 
وقتی محدودیت کاربر فعال میشه، بعضی از کاربرا مدام کانکشن اونا دراپ میشه، و قطع و وصل میشن. با یک گوشی هم فقط وصل هستن.
خیلی از کاربرا وقتی وصل هستن، ایپی دوم 127.0.0.1 براشون فعاله همزمان، میتونه ریشه مشکل تو همین باشه.
سیستم عامل : Ubuntu 18

**Comment by HamedAp** [comment]
بررسی میشه و اپدیت بعدی حتما درست میشه

**Comment by HamedAp** [comment]
اپدیت جدید مشکل حل شده .

**Comment by mory** [comment]
همچنان مشکل وجود دارد.
