### ISSUE TITLE
Project is not 'Open Source'

### ISSUE THREAD

**Issue by taheri79** [HamedAp/Ssh-User-management#72]
I Don't Know Why The source code of this project **isn't viewable** and all has been **encoded**.
Sorry _Hamed_ But we **develapers** do not **trust** _encoded php files_ because we are going to use it in **our servers** and its not **safe** to do that.
please provide a '_decoded_' version of your project.🙌

**Comment by HamedAp** [comment]
سلام . 
اوایل پروژه اوپن سورس بود . 
متاسفانه یه سری افراد سود جو پنل رو به قیمت بالایی به مردم در حال فروش بودند و مجبور شدم این کارو بکنم .

**Comment by FarzadMohtasham** [comment]
> شاید در اینده که لایسنس بهش اضافه بشه اوپن سورس کردم ! ولی فعلا چون در حال اپدیت هستیم امکان اوپن سورس بودن خیلی پایین هستش .

بسیار هم عالی، فقط آقا حامد به این ssh-calls.sh یه نگاهی بندازین، دهن سرور مارو سرویس کرد😂😂

**Comment by HamedAp** [comment]
> > شاید در اینده که لایسنس بهش اضافه بشه اوپن سورس کردم ! ولی فعلا چون در حال اپدیت هستیم امکان اوپن سورس بودن خیلی پایین هستش .
> 
> بسیار هم عالی، فقط آقا حامد به این ssh-calls.sh یه نگاهی بندازین، دهن سرور مارو سرویس کرد😂😂

چیشو نگا کنم ! 
کلا مصرفش بالاست . دست منم نیست

**Comment by FarzadMohtasham** [comment]
> > > شاید در اینده که لایسنس بهش اضافه بشه اوپن سورس کردم ! ولی فعلا چون در حال اپدیت هستیم امکان اوپن سورس بودن خیلی پایین هستش .
> > 
> > 
> > بسیار هم عالی، فقط آقا حامد به این ssh-calls.sh یه نگاهی بندازین، دهن سرور مارو سرویس کرد😂😂
> 
> چیشو نگا کنم ! کلا مصرفش بالاست . دست منم نیست

وقتی کسی از قابلیت زنگ زدن تو واتس‌اپ و تلگرام و... استفاده میکنه این اینطوری مصرفش میره بالا؟ یا همینطوری بدون هیچ دلیلی میره بالا

**Comment by HamedAp** [comment]
هر دو
