### ISSUE TITLE
مشکل در لیمیت تعداد استفاده همزمان

### ISSUE THREAD

**Issue by denizsoft** [HamedAp/Ssh-User-management#73]
چند تا باگ هست امیدوارم رفع بشه 
1 - لیمیت تعداد استفاده همزمان به درستی کار نمی کند
2 - امکان باز کردن پورت دلخواه روی ssh باید از طریق پنل فراهم باشد . فقط پورت 22 جوابگو نیست . موقع تعریف کاربر باید یک لیست کشویی باز بشه و بپرسه چه پورت هایی برای این کاربر فعال باشه و تیک زده بشه
3-سورس را به صورت دیکد شده منتشر کنید . تا اعتماد سازی بشه دوست عزیز

**Comment by HamedAp** [comment]
مورد اول در حال بررسی هستش 
مورد دوم به خاطر بعضی مواردی که تو کد نویسی هستش نمیشه از مولتی پورت استفاده کرد ! 
مورد سوم هم به خاطر سو استفاده یه عده دوستان ( فروش پنل با قیمت های فضایی به مردم بی خبر ) مجبور شدم انکود کنم .

**Comment by HamedAp** [comment]
پنل اپدیت کنین مشکل حل میشه
