### ISSUE TITLE
منقضی شدن یوزر 

### ISSUE THREAD

**Issue by shahrooz1349** [HamedAp/Ssh-User-management#74]
درود حامد عزیز و ممنون بابت شاهان پنل که بنظر میرسه جایگزین عالی برای v2ray باشه
من نصب کردم روی ابونتو 22.04 و عالی کار میده مشکل اینجاست یوزر رو یکماهه ایجاد کردم با حجم نامحدود اما بعد از گذشت 24 ساعت جای گزینه فعال کنار یوزر منقضی شد به نمایش در میاد و یوزر از کار میافته

**Comment by vanish666** [comment]
سلام و ارادت
ممنون بابت زحماتتون
برای منم این مشکل وجود داره

**Comment by HamedAp** [comment]
سلام وقت بخیر !
یا ترافیک واسش ثبت کردین که تموم شده ( دقت کنین ترافیک بر اساس مگابایت هستش ) 
یا تاریخ انقضا زدین .

**Comment by shahrooz1349** [comment]
حامد عزیز ممنون از پاسخ
احتمالا مشکل همین بوده بدون محدودیت حجم تست میکنم 🙏🌹
