### ISSUE TITLE
ایرنسل

### ISSUE THREAD

**Issue by nafiswal2** [HamedAp/Ssh-User-management#75]
با سلام ممنون از پنل خوبتون
فقط من هر کار کردم روی ایرانسل بهم جواب نداد روی همراه اول و وای فای عالی عمل کرد 
آیا برای ایرانسل راهی هست تا کار کنه ؟

**Comment by HamedAp** [comment]
سلام . 
از اپلیکیشن http injector  تو اندروید استفاده کنین و ای پی ورژن 6 بزنید ! 
داخل کانال تلگرام اموزش ای پی 6 رو زدیم . 
لینک کانال  :  https://t.me/ShaHaNPanel/15

**Comment by nafiswal2** [comment]
ممنون پاسخ سریعتون فقط رو آیفون به چه شکل هست چون من هر کار کردم با napesternetv نتونستم با آی پی 6 وصل بشم و انگار نیمشناسه
