### ISSUE TITLE
 عدم اتصال در مک و یک پیشنهاد

### ISSUE THREAD

**Issue by amir77xj** [HamedAp/Ssh-User-management#76]
سلام 
یه مشکلی که هست اینه که من با مک باید به این سرویس وصل بشم اما وقتی در ترمینال از sshuttle استفاده میکنم بلافاصله بعد از اتصال به سرور دسترسیم رو قطع میکنه سرور لطفا درستش کنین
و همچنین ممکنه که به یوزر ها هم دسترسی بدیم تا بتونن مدیریت کنن حجمشون و تعداد دستگاهشون رو؟

**Comment by HamedAp** [comment]
سلام . 
مک رو متاسفانه برنامه ای سراغ ندارم ! اینو میتونم بگم مشکل از پنل نیست برای وصل شدن ssh  . 
دسترسی به یوزر ها در اینده اضافه میشه ولی امکان فیلتر شدن با پنل کاربران هستش .
