### ISSUE TITLE
نشان دادن تعداد کاربرهای آنلاین

### ISSUE THREAD

**Issue by ExtremeDot** [HamedAp/Ssh-User-management#8]
![Untitled](https://user-images.githubusercontent.com/120102306/217458205-1e6c5afc-4c40-4436-9c86-11d6d3a1385a.png)

درود
آقا حامد، این مورد عادیه؟
تعداد کاربرهای متخلف و آنلاین؟ فقط یه یوزر ساختم برا تست

**Comment by HamedAp** [comment]
سلام .
پورت پیش فرض دارید ؟ ۲۲ ؟
پورت ssh رو شناسایی نکرده احتمالا تو فایل تنظیمات ssh پورت کامند شده .
#Port 22
اگه از ۲۲ استفاده میکنین اون هشتگ رو حذف کنین و دوباره نصب کنین .
ویا تو فایل های /var/www/html/p/menu.php و 
/var/www/html/p/kill.php 
خط دوم پورت رو وارد کنین .

**Comment by ExtremeDot** [comment]
تغییرات رو اعمال کردم، نتیجه رو اعلام میکنم بهتون
```sh
# nano /etc/ssh/sshd_config
Port 22

# systemctl restart sshd

# nano /var/www/html/p/menu.php
$port = "22";

# nano /var/www/html/p/kill.php
$port = "22";

# systemctl restart apache2

```

**Comment by ExtremeDot** [comment]
درست شد. مرسی
