### ISSUE TITLE
باز نشدن پنل بعد از عوض کردن پورت

### ISSUE THREAD

**Issue by ali-cloudy** [HamedAp/Ssh-User-management#81]
حامد مرسی عالی پرفکت . فقط ی ایراد ک از قدیم هست . پورت از داخل پنل عوض کردم و ذخیره بعدش دیگ نتونستم پنل باز کنم چ با آی پی چ دامنه . دلیلش چی می‌تونه باشه . الان من باید از اول اوبونتو پاک کنم و بنویسم!یا ؟! لطفا کمک

**Comment by HamedAp** [comment]
دستور نصب رو دوباره بزنین درست میشه

**Comment by artan-riseup** [comment]
مرسی آقا حامد گل . حتما
