### ISSUE TITLE
تعداد کاربر محدود نمیشه

### ISSUE THREAD

**Issue by abeddev** [HamedAp/Ssh-User-management#83]
محدودیت تعداد کاربر همزمان برای اکانت کار نمی کنه. لطفا یه بررسی کنین

**Comment by HamedAp** [comment]
کار میکنه !
توی تنظیمات محدودیت کاربر رو روشن کنین

**Comment by goodman77777** [comment]
سلام من محدودیت کاربر رو تست کردم و تونستم با چند دستگاه متصل بشم و  فقط باعث میشه که اگه همزمان وصل بشی کاربرا قطع و وصل میشن ، آیا راهی وجد نداره که وقتی یه کاربر وصله کاربر دیگه کلا نتونه متصل بشه  ؟
