### ISSUE TITLE
یوزر عمده

### ISSUE THREAD

**Issue by ali-cloudy** [HamedAp/Ssh-User-management#84]
درود . حامد عزیز تشکر و خسته نباشی دوست خوبم . عزیزم دو سوال . جای یک کانال برای جمع کردن افرادی ک در حال استفاده از پنل هستن و یا می‌خوان استفاده کنن و عیب یابی و رفع مشکل خالیه اگر بخوای میتونم تو این مورد کمک حالت باشم و اینکه من بعنوان تشکر بجای دونیت کردن رمز می‌خوام ی جور دیگ تشکر کنم . به انتخاب خودت ی سرور در نظر بگیر بعنوان هدیه می‌خوام بهت بدم . کاره من فروش سرور عزیزم یک ساله . تقریبا تو چهل تا دیتاسنتر اکانت فعال و واقعی و قابل استفاده دارم . کارت راحت می‌خوام بکنم . ازبین این چندتا یکی رو انتخاب کن برات تهیه کنم و بدم خدمتت . امریکا: ۲هسته سی پی ۸ گ رم . هاردnvme2 . آمریکا:۴سی پی .۸ گ رم .‌‌هارد۵۰۰. آمریکا:۴سی پی ۱۶گ‌ رم . ۱۲۰ گ‌ هارد .همشون پورت ی گیگ اختصاصی واقعی . و منابعشان کاملا اختصاصی . من تو کل کارام شیرینک ندارم .عربستان :۱ سی پی یو . ۲ گ‌ رم . پینگ ۱۲۰ ‌.ترکیه هم مثل عربستان . لندن مثل قبلی . روسیه هم همینطور . چک ۲ سی پی . ۲ گ‌ رم . تراف نامحدود . ژاپن: ۴ سی پی ۱۶ گ‌ رم . هلند ۲ هسته سی پی ۸ رم . مایکروسافت اژور هم بخوای اکانتش میدم بهت باهم استفاده کنیم ۱۷۰ دلار شارژ داره . هتزنر هم دارم با اعتبار ۵ ماهه و وریفای شخصی . و اینکه اگر بخوای برات اکانت قانونی light node درست میکنم و بهت میدم با ۱۰ دلار شارژ . رایگان البته . عشق دادی عشق می‌خوام بدم . مدارک بخوای دارم . پاس ای دی . گواهینامه . ش مجازی . اکانت چت جی وی تی . هرچی بگی تقدیمت میکنم . اگر برای کارتم سرور بخوای ک تست کنی و ... من رایگان در اختیارت میزارم . هیچ انتظاری ام ندارم ازت . دوتا سوال چرا پنل من امریکاش فیلتر شده ؟! چون از وی پی آن آمریکا استفاده میکنم ؟ و اینکه نمیتونم یوزر عمده بزنم . سوال بعد داداش من ی دونه یوزر دارم ۵۰ درصد از سی پی یو درگیره . باگه؟! راستی ایمیلمو میدم بهت بهم میل بزن ک بتونم درخدمتت باشم . 
راستی ی موقع دال بر تبلیغ کارم نشه من نیازی ب تبلیغ ندارم ی ساله کارمه . کانالم ۷ کا ممبر داره و وقت ندارم ج مشتریامو بدم پس لطفاً سو تفاهم بین دوستان پیش نیاد ‌‌لطفا لطفا. 

ali.sunycloudy@gmail.com
![Screenshot_2023-04-10-01-23-52-523_com android chrome-edit](https://user-images.githubusercontent.com/69906691/230799915-e4e8dfef-66ea-4717-ba6a-a7e7373f6026.jpg)

**Comment by ali-cloudy** [comment]
@HamedAp
آقا حامد محمد یه سوال دیگه میتونم تانل کنم پنل شمارو.اشنایی کامل یا تانل و ... و ... دارم فقط شما با یک بله یا ن جواب بدید ممنون میشم

**Comment by HamedAp** [comment]
سلام . 
ممنون بابت سرور ها . 
نیازی نیست مرسی .
در مورد سوالتون هم ای پی امریکا احتمالا نمیتونه وصل شه به سرورتون که میتونه موقت باشه . 

سوال دومتون یوزری که ساختین از پنل ساختین یا از دستور ؟

**Comment by ali-cloudy** [comment]
حامد جان اولا  ک من منتی ندارم سرت بزارم . چون دارم از پنلت استفاده میکنم .
و اینکه خودم دوست دارم به عنوان تشکر حداقل یه کاری برات کرده باشم و عزیزم
من از پنل شما استفاده می کنم نه کد .دوتا سوالم این بود یک راجع به یوزر عمده
که مشکلش حل شد فهمیدم دلیله اشتباه من چ بودش سوال دوم من این بود آیا میتونم
پنل شما رو روی تونل داشته باشم تمام پروتکل‌های تانل و بلدم و میدونم از کدام
پروتکل تانل استفاده بکنم و اینکه شما فقط تایید کنید که جواب میده برای من
کافیه. با اینکه من جسارت می کنم به سلیقه و انتخاب خودم یه سرور فوق‌العاده
برات فراهم می‌کنم و میدم خدمتت فقط نمیدونم چه جوری باید به دستت برسونم اینو
من نه آیدی از شما دارم نه چیز دیگه ای فکر کنم میل تو گیت هاب باشه به ایمیلت
بفرستم عزیزم.

**Comment by ali-cloudy** [comment]
تست کردم آقا حامد . باید اول ی لوکال تانل بزنیم رو سرور خارج ک‌بتونیم تانل
کنیم نمیشه که هم پورت مبدا و مقصد لوکال مثلا ۲۰۵۳ بگیریم هم پورت آس آس اچ .
ولی مجبوریم چون آس آس اچ استفاده میکنیم پورت اپ داخلی نداریم مث اپن و وایر
و و ..‌. ولی من با اجازتون ب کاره دیگ کردم کلا ای پی و دامنه ی اصلی رو
پنهان کردم . اگر قرار ب فیلتر باشه ساب سوم فیلتر میشه بعد دومی هست بعد ب
اولی برسن اونوقته ک فقط دی آن اس و نود ب دستشون میرسه و عملا سره فیلترینگ
سرور اصلیمون گرده . 🇺🇦💕
