### ISSUE TITLE
برداشتن مخفی کردن پسورد در هنگام ساخت یوزر

### ISSUE THREAD

**Issue by ExtremeDot** [HamedAp/Ssh-User-management#9]
![image](https://user-images.githubusercontent.com/120102306/217468473-71bfb745-ca5e-46cf-97f0-a89f510c7b20.png)

درود مجدد
حامد جان یه پیشنهاد، این مخفی بودن کلمات پسورد برا ساخت اکانت رو حذف کنید، آخه معلوم نیست چی داریم تایپ میکنیم، اشتباه تایپی باشه متوجه نمیشیم.

من مجبورم توی notepad بنویسم بعد اینجا paste کنم

**Comment by HamedAp** [comment]
انشالله در اپدیت بعدی اعمال میشه

**Comment by HamedAp** [comment]
با سلام . اعمال شد .
