### ISSUE TITLE
user back up

### ISSUE THREAD

**Issue by mohsen9lion** [HamedAp/Ssh-User-management#96]
بک آب گرفتم اما رو سرور جدید ریستور میکنم نمیشه ؟ ایا باید ورژن اوبونتو یکی باشه ؟

**Comment by HamedAp** [comment]
سلام . 
نه نباید مشکلی داشته باشه .  
یوزر هارو نمیاره یا چی ؟ مشکل چیه

**Comment by mohsen9lion** [comment]
بعد از آپلود کردن اون فایل SQL هیچ یوزری رو نشون نمیده
